//! Bulk operations for ProductCategory entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateProductCategoryDto;
use crate::application::service::ProductCategoryService;
use crate::domain::entity::ProductCategory;

/// Bulk operation handler for ProductCategory entities.
///
/// Wraps `ProductCategoryService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ProductCategoryBulkService = GenericBulkService<ProductCategory, CreateProductCategoryDto, ProductCategoryService>;

// <<< CUSTOM
// END CUSTOM
