//! Bulk operations for StockItem entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateStockItemDto;
use crate::application::service::StockItemService;
use crate::domain::entity::StockItem;

/// Bulk operation handler for StockItem entities.
///
/// Wraps `StockItemService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type StockItemBulkService = GenericBulkService<StockItem, CreateStockItemDto, StockItemService>;

// <<< CUSTOM
// END CUSTOM
