//! Bulk operations for StockBatch entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateStockBatchDto;
use crate::application::service::StockBatchService;
use crate::domain::entity::StockBatch;

/// Bulk operation handler for StockBatch entities.
///
/// Wraps `StockBatchService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type StockBatchBulkService = GenericBulkService<StockBatch, CreateStockBatchDto, StockBatchService>;

// <<< CUSTOM
// END CUSTOM
