//! Bulk operations for StockEntry entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateStockEntryDto;
use crate::application::service::StockEntryService;
use crate::domain::entity::StockEntry;

/// Bulk operation handler for StockEntry entities.
///
/// Wraps `StockEntryService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type StockEntryBulkService = GenericBulkService<StockEntry, CreateStockEntryDto, StockEntryService>;

// <<< CUSTOM
// END CUSTOM
