//! GoodsReceiptItem DTOs (Data Transfer Objects)
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::GoodsReceiptItem;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::QCResult;
use crate::domain::entity::ReceiptItemStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new GoodsReceiptItem
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateGoodsReceiptItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub goods_receipt_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub product_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub purchase_order_item_id: Option<Uuid>,
    pub ordered_quantity: Decimal,
    pub received_quantity: Decimal,
    pub accepted_quantity: Decimal,
    pub rejected_quantity: Decimal,
    pub variance_quantity: Decimal,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub uom: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_uom_quantity: Option<Decimal>,
    pub conversion_factor: Decimal,
    pub unit_cost: Decimal,
    pub total_cost: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub batch_number: Option<String>,
    pub serial_numbers: serde_json::Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub manufacture_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expiry_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub warehouse_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bin_location: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub requires_qc: bool,
    pub qc_result: QCResult,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub qc_date: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub qc_by: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub qc_notes: Option<String>,
    pub qc_parameters: serde_json::Value,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rejection_reason: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rejection_action: Option<String>,
    pub status: ReceiptItemStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stock_movement_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_posted: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub posted_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a GoodsReceiptItem
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateGoodsReceiptItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub goods_receipt_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub product_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub purchase_order_item_id: Option<Uuid>,
    pub ordered_quantity: Decimal,
    pub received_quantity: Decimal,
    pub accepted_quantity: Decimal,
    pub rejected_quantity: Decimal,
    pub variance_quantity: Decimal,
    #[cfg_attr(feature = "validation", validate(length(max = 20)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub uom: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_uom_quantity: Option<Decimal>,
    pub conversion_factor: Decimal,
    pub unit_cost: Decimal,
    pub total_cost: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub batch_number: Option<String>,
    pub serial_numbers: serde_json::Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub manufacture_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expiry_date: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub warehouse_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bin_location: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub requires_qc: bool,
    pub qc_result: QCResult,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub qc_date: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub qc_by: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub qc_notes: Option<String>,
    pub qc_parameters: serde_json::Value,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rejection_reason: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 30)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rejection_action: Option<String>,
    pub status: ReceiptItemStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stock_movement_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_posted: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub posted_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a GoodsReceiptItem
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchGoodsReceiptItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub goods_receipt_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub product_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub purchase_order_item_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ordered_quantity: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub received_quantity: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub accepted_quantity: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rejected_quantity: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub variance_quantity: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uom: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub base_uom_quantity: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conversion_factor: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unit_cost: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_cost: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub batch_number: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub serial_numbers: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub manufacture_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expiry_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub warehouse_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bin_location: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub requires_qc: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub qc_result: Option<QCResult>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub qc_date: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub qc_by: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub qc_notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub qc_parameters: Option<serde_json::Value>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rejection_reason: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rejection_action: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<ReceiptItemStatus>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stock_movement_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_posted: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub posted_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

impl PatchGoodsReceiptItemDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.goods_receipt_id.is_some() || self.product_id.is_some() || self.purchase_order_item_id.is_some() || self.ordered_quantity.is_some() || self.received_quantity.is_some() || self.accepted_quantity.is_some() || self.rejected_quantity.is_some() || self.variance_quantity.is_some() || self.uom.is_some() || self.base_uom_quantity.is_some() || self.conversion_factor.is_some() || self.unit_cost.is_some() || self.total_cost.is_some() || self.currency.is_some() || self.batch_number.is_some() || self.serial_numbers.is_some() || self.manufacture_date.is_some() || self.expiry_date.is_some() || self.warehouse_id.is_some() || self.bin_location.is_some() || self.requires_qc.is_some() || self.qc_result.is_some() || self.qc_date.is_some() || self.qc_by.is_some() || self.qc_notes.is_some() || self.qc_parameters.is_some() || self.rejection_reason.is_some() || self.rejection_action.is_some() || self.status.is_some() || self.stock_movement_id.is_some() || self.is_posted.is_some() || self.posted_at.is_some() || self.notes.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for GoodsReceiptItem entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GoodsReceiptItemResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub goods_receipt_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub product_id: Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub purchase_order_item_id: Option<Uuid>,
    pub ordered_quantity: Decimal,
    pub received_quantity: Decimal,
    pub accepted_quantity: Decimal,
    pub rejected_quantity: Decimal,
    pub variance_quantity: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub uom: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub base_uom_quantity: Option<Decimal>,
    pub conversion_factor: Decimal,
    pub unit_cost: Decimal,
    pub total_cost: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub batch_number: Option<String>,
    pub serial_numbers: serde_json::Value,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub manufacture_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expiry_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub warehouse_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bin_location: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub requires_qc: bool,
    pub qc_result: QCResult,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub qc_date: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub qc_by: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub qc_notes: Option<String>,
    pub qc_parameters: serde_json::Value,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rejection_reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rejection_action: Option<String>,
    pub status: ReceiptItemStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stock_movement_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_posted: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub posted_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for GoodsReceiptItem entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GoodsReceiptItemListResponseDto {
    /// List of items
    pub items: Vec<GoodsReceiptItemResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl GoodsReceiptItemListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<GoodsReceiptItemResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct GoodsReceiptItemSummaryDto {
    pub id: Uuid,
    pub goods_receipt_id: Uuid,
    pub product_id: Uuid,
    pub purchase_order_item_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<GoodsReceiptItem> for GoodsReceiptItemResponseDto {
    fn from(entity: GoodsReceiptItem) -> Self {
        Self {
            id: entity.id,
            goods_receipt_id: entity.goods_receipt_id,
            product_id: entity.product_id,
            purchase_order_item_id: entity.purchase_order_item_id,
            ordered_quantity: entity.ordered_quantity,
            received_quantity: entity.received_quantity,
            accepted_quantity: entity.accepted_quantity,
            rejected_quantity: entity.rejected_quantity,
            variance_quantity: entity.variance_quantity,
            uom: entity.uom,
            base_uom_quantity: entity.base_uom_quantity,
            conversion_factor: entity.conversion_factor,
            unit_cost: entity.unit_cost,
            total_cost: entity.total_cost,
            currency: entity.currency,
            batch_number: entity.batch_number,
            serial_numbers: entity.serial_numbers,
            manufacture_date: entity.manufacture_date,
            expiry_date: entity.expiry_date,
            warehouse_id: entity.warehouse_id,
            bin_location: entity.bin_location,
            requires_qc: entity.requires_qc,
            qc_result: entity.qc_result,
            qc_date: entity.qc_date,
            qc_by: entity.qc_by,
            qc_notes: entity.qc_notes,
            qc_parameters: entity.qc_parameters,
            rejection_reason: entity.rejection_reason,
            rejection_action: entity.rejection_action,
            status: entity.status,
            stock_movement_id: entity.stock_movement_id,
            is_posted: entity.is_posted,
            posted_at: entity.posted_at,
            notes: entity.notes,
            metadata: entity.metadata,
        }
    }
}

impl From<GoodsReceiptItem> for GoodsReceiptItemSummaryDto {
    fn from(entity: GoodsReceiptItem) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            goods_receipt_id: entity.goods_receipt_id,
            product_id: entity.product_id,
            purchase_order_item_id: entity.purchase_order_item_id,
            created_at,
        }
    }
}

impl From<CreateGoodsReceiptItemDto> for GoodsReceiptItem {
    fn from(dto: CreateGoodsReceiptItemDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            goods_receipt_id: dto.goods_receipt_id,
            product_id: dto.product_id,
            purchase_order_item_id: dto.purchase_order_item_id,
            ordered_quantity: dto.ordered_quantity,
            received_quantity: dto.received_quantity,
            accepted_quantity: dto.accepted_quantity,
            rejected_quantity: dto.rejected_quantity,
            variance_quantity: dto.variance_quantity,
            uom: dto.uom,
            base_uom_quantity: dto.base_uom_quantity,
            conversion_factor: dto.conversion_factor,
            unit_cost: dto.unit_cost,
            total_cost: dto.total_cost,
            currency: dto.currency,
            batch_number: dto.batch_number,
            serial_numbers: dto.serial_numbers,
            manufacture_date: dto.manufacture_date,
            expiry_date: dto.expiry_date,
            warehouse_id: dto.warehouse_id,
            bin_location: dto.bin_location,
            requires_qc: dto.requires_qc,
            qc_result: dto.qc_result,
            qc_date: dto.qc_date,
            qc_by: dto.qc_by,
            qc_notes: dto.qc_notes,
            qc_parameters: dto.qc_parameters,
            rejection_reason: dto.rejection_reason,
            rejection_action: dto.rejection_action,
            status: dto.status,
            stock_movement_id: dto.stock_movement_id,
            is_posted: dto.is_posted,
            posted_at: dto.posted_at,
            notes: dto.notes,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&GoodsReceiptItem> for GoodsReceiptItemResponseDto {
    fn from(entity: &GoodsReceiptItem) -> Self {
        Self {
            id: entity.id.clone(),
            goods_receipt_id: entity.goods_receipt_id.clone(),
            product_id: entity.product_id.clone(),
            purchase_order_item_id: entity.purchase_order_item_id.clone(),
            ordered_quantity: entity.ordered_quantity.clone(),
            received_quantity: entity.received_quantity.clone(),
            accepted_quantity: entity.accepted_quantity.clone(),
            rejected_quantity: entity.rejected_quantity.clone(),
            variance_quantity: entity.variance_quantity.clone(),
            uom: entity.uom.clone(),
            base_uom_quantity: entity.base_uom_quantity.clone(),
            conversion_factor: entity.conversion_factor.clone(),
            unit_cost: entity.unit_cost.clone(),
            total_cost: entity.total_cost.clone(),
            currency: entity.currency.clone(),
            batch_number: entity.batch_number.clone(),
            serial_numbers: entity.serial_numbers.clone(),
            manufacture_date: entity.manufacture_date.clone(),
            expiry_date: entity.expiry_date.clone(),
            warehouse_id: entity.warehouse_id.clone(),
            bin_location: entity.bin_location.clone(),
            requires_qc: entity.requires_qc.clone(),
            qc_result: entity.qc_result.clone(),
            qc_date: entity.qc_date.clone(),
            qc_by: entity.qc_by.clone(),
            qc_notes: entity.qc_notes.clone(),
            qc_parameters: entity.qc_parameters.clone(),
            rejection_reason: entity.rejection_reason.clone(),
            rejection_action: entity.rejection_action.clone(),
            status: entity.status.clone(),
            stock_movement_id: entity.stock_movement_id.clone(),
            is_posted: entity.is_posted.clone(),
            posted_at: entity.posted_at.clone(),
            notes: entity.notes.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateGoodsReceiptItemDto> for GoodsReceiptItem {
    fn from_create_dto(dto: CreateGoodsReceiptItemDto) -> backbone_core::ServiceResult<Self> {
        Ok(GoodsReceiptItem::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateGoodsReceiptItemDto> for GoodsReceiptItem {
    fn apply_update(mut self, dto: UpdateGoodsReceiptItemDto) -> backbone_core::ServiceResult<Self> {
        self.goods_receipt_id = dto.goods_receipt_id;
        self.product_id = dto.product_id;
        self.purchase_order_item_id = dto.purchase_order_item_id;
        self.ordered_quantity = dto.ordered_quantity;
        self.received_quantity = dto.received_quantity;
        self.accepted_quantity = dto.accepted_quantity;
        self.rejected_quantity = dto.rejected_quantity;
        self.variance_quantity = dto.variance_quantity;
        self.uom = dto.uom;
        self.base_uom_quantity = dto.base_uom_quantity;
        self.conversion_factor = dto.conversion_factor;
        self.unit_cost = dto.unit_cost;
        self.total_cost = dto.total_cost;
        self.currency = dto.currency;
        self.batch_number = dto.batch_number;
        self.serial_numbers = dto.serial_numbers;
        self.manufacture_date = dto.manufacture_date;
        self.expiry_date = dto.expiry_date;
        self.warehouse_id = dto.warehouse_id;
        self.bin_location = dto.bin_location;
        self.requires_qc = dto.requires_qc;
        self.qc_result = dto.qc_result;
        self.qc_date = dto.qc_date;
        self.qc_by = dto.qc_by;
        self.qc_notes = dto.qc_notes;
        self.qc_parameters = dto.qc_parameters;
        self.rejection_reason = dto.rejection_reason;
        self.rejection_action = dto.rejection_action;
        self.status = dto.status;
        self.stock_movement_id = dto.stock_movement_id;
        self.is_posted = dto.is_posted;
        self.posted_at = dto.posted_at;
        self.notes = dto.notes;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to GoodsReceiptItem here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

