//! OperationType DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::OperationType;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::CreateBackorder;
use crate::domain::entity::MoveType;
use crate::domain::entity::PickingCode;
use crate::domain::entity::ReservationMethod;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new OperationType
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateOperationTypeDto {
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "sequence_code")]
    pub sequence_code: String,
    pub code: PickingCode,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "warehouse_id")]
    pub warehouse_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "default_location_src_id")]
    pub default_location_src_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "default_location_dest_id")]
    pub default_location_dest_id: Uuid,
    #[serde(alias = "reservation_method")]
    pub reservation_method: ReservationMethod,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reservation_days_before")]
    pub reservation_days_before: Option<i32>,
    #[serde(alias = "move_type")]
    pub move_type: MoveType,
    #[serde(alias = "create_backorder")]
    pub create_backorder: CreateBackorder,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "use_create_lots")]
    pub use_create_lots: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "use_existing_lots")]
    pub use_existing_lots: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a OperationType
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateOperationTypeDto {
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "sequence_code")]
    pub sequence_code: String,
    pub code: PickingCode,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "warehouse_id")]
    pub warehouse_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "default_location_src_id")]
    pub default_location_src_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "default_location_dest_id")]
    pub default_location_dest_id: Uuid,
    #[serde(alias = "reservation_method")]
    pub reservation_method: ReservationMethod,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reservation_days_before")]
    pub reservation_days_before: Option<i32>,
    #[serde(alias = "move_type")]
    pub move_type: MoveType,
    #[serde(alias = "create_backorder")]
    pub create_backorder: CreateBackorder,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "use_create_lots")]
    pub use_create_lots: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "use_existing_lots")]
    pub use_existing_lots: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a OperationType
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchOperationTypeDto {
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "sequence_code")]
    pub sequence_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<PickingCode>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sequence: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "warehouse_id")]
    pub warehouse_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "default_location_src_id")]
    pub default_location_src_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "default_location_dest_id")]
    pub default_location_dest_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "reservation_method")]
    pub reservation_method: Option<ReservationMethod>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "reservation_days_before")]
    pub reservation_days_before: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "move_type")]
    pub move_type: Option<MoveType>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "create_backorder")]
    pub create_backorder: Option<CreateBackorder>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "use_create_lots")]
    pub use_create_lots: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "use_existing_lots")]
    pub use_existing_lots: Option<bool>,
}

impl PatchOperationTypeDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.name.is_some() || self.sequence_code.is_some() || self.code.is_some() || self.active.is_some() || self.sequence.is_some() || self.company_id.is_some() || self.warehouse_id.is_some() || self.default_location_src_id.is_some() || self.default_location_dest_id.is_some() || self.reservation_method.is_some() || self.reservation_days_before.is_some() || self.move_type.is_some() || self.create_backorder.is_some() || self.use_create_lots.is_some() || self.use_existing_lots.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for OperationType entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OperationTypeResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub sequence_code: String,
    pub code: PickingCode,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub sequence: i32,
    pub company_id: Option<Uuid>,
    pub warehouse_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub default_location_src_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub default_location_dest_id: Uuid,
    pub reservation_method: ReservationMethod,
    pub reservation_days_before: Option<i32>,
    pub move_type: MoveType,
    pub create_backorder: CreateBackorder,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub use_create_lots: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub use_existing_lots: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for OperationType entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OperationTypeListResponseDto {
    /// List of items
    pub items: Vec<OperationTypeResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl OperationTypeListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<OperationTypeResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OperationTypeSummaryDto {
    pub id: Uuid,
    pub name: String,
    pub sequence_code: String,
    pub code: PickingCode,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<OperationType> for OperationTypeResponseDto {
    fn from(entity: OperationType) -> Self {
        Self {
            id: entity.id,
            name: entity.name,
            sequence_code: entity.sequence_code,
            code: entity.code,
            active: entity.active,
            sequence: entity.sequence,
            company_id: entity.company_id,
            warehouse_id: entity.warehouse_id,
            default_location_src_id: entity.default_location_src_id,
            default_location_dest_id: entity.default_location_dest_id,
            reservation_method: entity.reservation_method,
            reservation_days_before: entity.reservation_days_before,
            move_type: entity.move_type,
            create_backorder: entity.create_backorder,
            use_create_lots: entity.use_create_lots,
            use_existing_lots: entity.use_existing_lots,
            metadata: entity.metadata,
        }
    }
}

impl From<OperationType> for OperationTypeSummaryDto {
    fn from(entity: OperationType) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            name: entity.name,
            sequence_code: entity.sequence_code,
            code: entity.code,
            created_at,
        }
    }
}

impl From<CreateOperationTypeDto> for OperationType {
    fn from(dto: CreateOperationTypeDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: dto.name,
            sequence_code: dto.sequence_code,
            code: dto.code,
            active: dto.active,
            sequence: dto.sequence,
            company_id: dto.company_id,
            warehouse_id: dto.warehouse_id,
            default_location_src_id: dto.default_location_src_id,
            default_location_dest_id: dto.default_location_dest_id,
            reservation_method: dto.reservation_method,
            reservation_days_before: dto.reservation_days_before,
            move_type: dto.move_type,
            create_backorder: dto.create_backorder,
            use_create_lots: dto.use_create_lots,
            use_existing_lots: dto.use_existing_lots,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&OperationType> for OperationTypeResponseDto {
    fn from(entity: &OperationType) -> Self {
        Self {
            id: entity.id.clone(),
            name: entity.name.clone(),
            sequence_code: entity.sequence_code.clone(),
            code: entity.code.clone(),
            active: entity.active.clone(),
            sequence: entity.sequence.clone(),
            company_id: entity.company_id.clone(),
            warehouse_id: entity.warehouse_id.clone(),
            default_location_src_id: entity.default_location_src_id.clone(),
            default_location_dest_id: entity.default_location_dest_id.clone(),
            reservation_method: entity.reservation_method.clone(),
            reservation_days_before: entity.reservation_days_before.clone(),
            move_type: entity.move_type.clone(),
            create_backorder: entity.create_backorder.clone(),
            use_create_lots: entity.use_create_lots.clone(),
            use_existing_lots: entity.use_existing_lots.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateOperationTypeDto> for OperationType {
    fn from_create_dto(dto: CreateOperationTypeDto) -> backbone_core::ServiceResult<Self> {
        Ok(OperationType::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateOperationTypeDto> for OperationType {
    fn apply_update(mut self, dto: UpdateOperationTypeDto) -> backbone_core::ServiceResult<Self> {
        self.name = dto.name;
        self.sequence_code = dto.sequence_code;
        self.code = dto.code;
        self.active = dto.active;
        self.sequence = dto.sequence;
        self.company_id = dto.company_id;
        self.warehouse_id = dto.warehouse_id;
        self.default_location_src_id = dto.default_location_src_id;
        self.default_location_dest_id = dto.default_location_dest_id;
        self.reservation_method = dto.reservation_method;
        self.reservation_days_before = dto.reservation_days_before;
        self.move_type = dto.move_type;
        self.create_backorder = dto.create_backorder;
        self.use_create_lots = dto.use_create_lots;
        self.use_existing_lots = dto.use_existing_lots;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to OperationType here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
