//! StockAdjustmentItem DTOs (Data Transfer Objects)
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::StockAdjustmentItem;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::UnitOfMeasure;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new StockAdjustmentItem
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateStockAdjustmentItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub adjustment_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub provider_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub line_number: i32,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub product_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub stock_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub batch_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub batch_number: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expiry_date: Option<NaiveDate>,
    pub uom: UnitOfMeasure,
    pub system_quantity: Decimal,
    pub counted_quantity: Decimal,
    pub variance_quantity: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub unit_cost: Decimal,
    pub system_value: Decimal,
    pub adjustment_value: Decimal,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub variance_reason: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bin_location: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_posted: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub movement_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    pub data: serde_json::Value,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a StockAdjustmentItem
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateStockAdjustmentItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub adjustment_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub provider_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub line_number: i32,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub product_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub stock_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub batch_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub batch_number: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expiry_date: Option<NaiveDate>,
    pub uom: UnitOfMeasure,
    pub system_quantity: Decimal,
    pub counted_quantity: Decimal,
    pub variance_quantity: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub unit_cost: Decimal,
    pub system_value: Decimal,
    pub adjustment_value: Decimal,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub variance_reason: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bin_location: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_posted: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub movement_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    pub data: serde_json::Value,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a StockAdjustmentItem
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchStockAdjustmentItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub adjustment_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub line_number: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub product_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stock_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub batch_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub batch_number: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expiry_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uom: Option<UnitOfMeasure>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_quantity: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub counted_quantity: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub variance_quantity: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unit_cost: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system_value: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub adjustment_value: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub variance_reason: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bin_location: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_posted: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub movement_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
}

impl PatchStockAdjustmentItemDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.adjustment_id.is_some() || self.provider_id.is_some() || self.line_number.is_some() || self.product_id.is_some() || self.stock_id.is_some() || self.batch_id.is_some() || self.batch_number.is_some() || self.expiry_date.is_some() || self.uom.is_some() || self.system_quantity.is_some() || self.counted_quantity.is_some() || self.variance_quantity.is_some() || self.currency.is_some() || self.unit_cost.is_some() || self.system_value.is_some() || self.adjustment_value.is_some() || self.variance_reason.is_some() || self.bin_location.is_some() || self.is_posted.is_some() || self.movement_id.is_some() || self.notes.is_some() || self.data.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for StockAdjustmentItem entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct StockAdjustmentItemResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub adjustment_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub provider_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub line_number: i32,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub product_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub stock_id: Uuid,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub batch_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub batch_number: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expiry_date: Option<NaiveDate>,
    pub uom: UnitOfMeasure,
    pub system_quantity: Decimal,
    pub counted_quantity: Decimal,
    pub variance_quantity: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub unit_cost: Decimal,
    pub system_value: Decimal,
    pub adjustment_value: Decimal,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub variance_reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bin_location: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_posted: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub movement_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    pub data: serde_json::Value,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for StockAdjustmentItem entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct StockAdjustmentItemListResponseDto {
    /// List of items
    pub items: Vec<StockAdjustmentItemResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl StockAdjustmentItemListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<StockAdjustmentItemResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct StockAdjustmentItemSummaryDto {
    pub id: Uuid,
    pub adjustment_id: Uuid,
    pub provider_id: Uuid,
    pub line_number: i32,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<StockAdjustmentItem> for StockAdjustmentItemResponseDto {
    fn from(entity: StockAdjustmentItem) -> Self {
        Self {
            id: entity.id,
            adjustment_id: entity.adjustment_id,
            provider_id: entity.provider_id,
            line_number: entity.line_number,
            product_id: entity.product_id,
            stock_id: entity.stock_id,
            batch_id: entity.batch_id,
            batch_number: entity.batch_number,
            expiry_date: entity.expiry_date,
            uom: entity.uom,
            system_quantity: entity.system_quantity,
            counted_quantity: entity.counted_quantity,
            variance_quantity: entity.variance_quantity,
            currency: entity.currency,
            unit_cost: entity.unit_cost,
            system_value: entity.system_value,
            adjustment_value: entity.adjustment_value,
            variance_reason: entity.variance_reason,
            bin_location: entity.bin_location,
            is_posted: entity.is_posted,
            movement_id: entity.movement_id,
            notes: entity.notes,
            data: entity.data,
            metadata: entity.metadata,
        }
    }
}

impl From<StockAdjustmentItem> for StockAdjustmentItemSummaryDto {
    fn from(entity: StockAdjustmentItem) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            adjustment_id: entity.adjustment_id,
            provider_id: entity.provider_id,
            line_number: entity.line_number,
            created_at,
        }
    }
}

impl From<CreateStockAdjustmentItemDto> for StockAdjustmentItem {
    fn from(dto: CreateStockAdjustmentItemDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            adjustment_id: dto.adjustment_id,
            provider_id: dto.provider_id,
            line_number: dto.line_number,
            product_id: dto.product_id,
            stock_id: dto.stock_id,
            batch_id: dto.batch_id,
            batch_number: dto.batch_number,
            expiry_date: dto.expiry_date,
            uom: dto.uom,
            system_quantity: dto.system_quantity,
            counted_quantity: dto.counted_quantity,
            variance_quantity: dto.variance_quantity,
            currency: dto.currency,
            unit_cost: dto.unit_cost,
            system_value: dto.system_value,
            adjustment_value: dto.adjustment_value,
            variance_reason: dto.variance_reason,
            bin_location: dto.bin_location,
            is_posted: dto.is_posted,
            movement_id: dto.movement_id,
            notes: dto.notes,
            data: dto.data,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&StockAdjustmentItem> for StockAdjustmentItemResponseDto {
    fn from(entity: &StockAdjustmentItem) -> Self {
        Self {
            id: entity.id.clone(),
            adjustment_id: entity.adjustment_id.clone(),
            provider_id: entity.provider_id.clone(),
            line_number: entity.line_number.clone(),
            product_id: entity.product_id.clone(),
            stock_id: entity.stock_id.clone(),
            batch_id: entity.batch_id.clone(),
            batch_number: entity.batch_number.clone(),
            expiry_date: entity.expiry_date.clone(),
            uom: entity.uom.clone(),
            system_quantity: entity.system_quantity.clone(),
            counted_quantity: entity.counted_quantity.clone(),
            variance_quantity: entity.variance_quantity.clone(),
            currency: entity.currency.clone(),
            unit_cost: entity.unit_cost.clone(),
            system_value: entity.system_value.clone(),
            adjustment_value: entity.adjustment_value.clone(),
            variance_reason: entity.variance_reason.clone(),
            bin_location: entity.bin_location.clone(),
            is_posted: entity.is_posted.clone(),
            movement_id: entity.movement_id.clone(),
            notes: entity.notes.clone(),
            data: entity.data.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateStockAdjustmentItemDto> for StockAdjustmentItem {
    fn from_create_dto(dto: CreateStockAdjustmentItemDto) -> backbone_core::ServiceResult<Self> {
        Ok(StockAdjustmentItem::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateStockAdjustmentItemDto> for StockAdjustmentItem {
    fn apply_update(mut self, dto: UpdateStockAdjustmentItemDto) -> backbone_core::ServiceResult<Self> {
        self.adjustment_id = dto.adjustment_id;
        self.provider_id = dto.provider_id;
        self.line_number = dto.line_number;
        self.product_id = dto.product_id;
        self.stock_id = dto.stock_id;
        self.batch_id = dto.batch_id;
        self.batch_number = dto.batch_number;
        self.expiry_date = dto.expiry_date;
        self.uom = dto.uom;
        self.system_quantity = dto.system_quantity;
        self.counted_quantity = dto.counted_quantity;
        self.variance_quantity = dto.variance_quantity;
        self.currency = dto.currency;
        self.unit_cost = dto.unit_cost;
        self.system_value = dto.system_value;
        self.adjustment_value = dto.adjustment_value;
        self.variance_reason = dto.variance_reason;
        self.bin_location = dto.bin_location;
        self.is_posted = dto.is_posted;
        self.movement_id = dto.movement_id;
        self.notes = dto.notes;
        self.data = dto.data;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to StockAdjustmentItem here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

