//! StorageCategory DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::StorageCategory;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::StorageAllowNewProduct;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new StorageCategory
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateStorageCategoryDto {
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "max_weight")]
    pub max_weight: Option<Decimal>,
    #[serde(alias = "allow_new_product")]
    pub allow_new_product: StorageAllowNewProduct,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a StorageCategory
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateStorageCategoryDto {
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "max_weight")]
    pub max_weight: Option<Decimal>,
    #[serde(alias = "allow_new_product")]
    pub allow_new_product: StorageAllowNewProduct,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a StorageCategory
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchStorageCategoryDto {
    #[cfg_attr(feature = "validation", validate(length(max = 150)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "max_weight")]
    pub max_weight: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "allow_new_product")]
    pub allow_new_product: Option<StorageAllowNewProduct>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
}

impl PatchStorageCategoryDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.name.is_some() || self.max_weight.is_some() || self.allow_new_product.is_some() || self.active.is_some() || self.company_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for StorageCategory entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct StorageCategoryResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub max_weight: Option<Decimal>,
    pub allow_new_product: StorageAllowNewProduct,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub active: bool,
    pub company_id: Option<Uuid>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for StorageCategory entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct StorageCategoryListResponseDto {
    /// List of items
    pub items: Vec<StorageCategoryResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl StorageCategoryListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<StorageCategoryResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct StorageCategorySummaryDto {
    pub id: Uuid,
    pub name: String,
    pub max_weight: Option<Decimal>,
    pub allow_new_product: StorageAllowNewProduct,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<StorageCategory> for StorageCategoryResponseDto {
    fn from(entity: StorageCategory) -> Self {
        Self {
            id: entity.id,
            name: entity.name,
            max_weight: entity.max_weight,
            allow_new_product: entity.allow_new_product,
            active: entity.active,
            company_id: entity.company_id,
            metadata: entity.metadata,
        }
    }
}

impl From<StorageCategory> for StorageCategorySummaryDto {
    fn from(entity: StorageCategory) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            name: entity.name,
            max_weight: entity.max_weight,
            allow_new_product: entity.allow_new_product,
            created_at,
        }
    }
}

impl From<CreateStorageCategoryDto> for StorageCategory {
    fn from(dto: CreateStorageCategoryDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: dto.name,
            max_weight: dto.max_weight,
            allow_new_product: dto.allow_new_product,
            active: dto.active,
            company_id: dto.company_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&StorageCategory> for StorageCategoryResponseDto {
    fn from(entity: &StorageCategory) -> Self {
        Self {
            id: entity.id.clone(),
            name: entity.name.clone(),
            max_weight: entity.max_weight.clone(),
            allow_new_product: entity.allow_new_product.clone(),
            active: entity.active.clone(),
            company_id: entity.company_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateStorageCategoryDto> for StorageCategory {
    fn from_create_dto(dto: CreateStorageCategoryDto) -> backbone_core::ServiceResult<Self> {
        Ok(StorageCategory::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateStorageCategoryDto> for StorageCategory {
    fn apply_update(mut self, dto: UpdateStorageCategoryDto) -> backbone_core::ServiceResult<Self> {
        self.name = dto.name;
        self.max_weight = dto.max_weight;
        self.allow_new_product = dto.allow_new_product;
        self.active = dto.active;
        self.company_id = dto.company_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to StorageCategory here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
