//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod delivery_note_specification;
pub mod delivery_note_item_specification;
pub mod purchase_receipt_specification;
pub mod purchase_receipt_item_specification;
pub mod stock_entry_specification;
pub mod stock_entry_item_specification;
pub mod stock_ledger_entry_specification;
pub mod bin_specification;
pub mod stock_reconciliation_specification;
pub mod stock_reconciliation_item_specification;
pub mod warehouse_specification;
pub mod stock_item_specification;

// <<< CUSTOM
// END CUSTOM
