//! Domain policy for PurchaseReceiptItem aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::PurchaseReceiptItem;

/// Domain policy for PurchaseReceiptItem — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<PurchaseReceiptItem>` in the `// <<< CUSTOM` zone.
pub type PurchaseReceiptItemDomainPolicy = PermitAllPolicy<PurchaseReceiptItem>;

// <<< CUSTOM
// END CUSTOM
