//! Domain policy for StockTransferItem aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::StockTransferItem;

/// Domain policy for StockTransferItem — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<StockTransferItem>` in the `// <<< CUSTOM` zone.
pub type StockTransferItemDomainPolicy = PermitAllPolicy<StockTransferItem>;

// <<< CUSTOM
// END CUSTOM
