//! Application service for InventoryCompanySetting entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `inventory_company_setting_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateInventoryCompanySettingDto, UpdateInventoryCompanySettingDto};
use crate::domain::entity::InventoryCompanySetting;
use crate::infrastructure::persistence::InventoryCompanySettingRepository;

/// Application service for InventoryCompanySetting entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `inventory_company_setting_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct InventoryCompanySettingServiceCustom {
///     inner: Arc<InventoryCompanySettingService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type InventoryCompanySettingService = GenericCrudService<
    InventoryCompanySetting,
    CreateInventoryCompanySettingDto,
    UpdateInventoryCompanySettingDto,
    InventoryCompanySettingRepository,
>;

// <<< CUSTOM
// END CUSTOM
