//! Application service for LandedCostLine entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `landed_cost_line_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateLandedCostLineDto, UpdateLandedCostLineDto};
use crate::domain::entity::LandedCostLine;
use crate::infrastructure::persistence::LandedCostLineRepository;

/// Application service for LandedCostLine entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `landed_cost_line_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct LandedCostLineServiceCustom {
///     inner: Arc<LandedCostLineService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type LandedCostLineService = GenericCrudService<
    LandedCostLine,
    CreateLandedCostLineDto,
    UpdateLandedCostLineDto,
    LandedCostLineRepository,
>;

// <<< CUSTOM
// END CUSTOM
