//! Application service for OperationType entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `operation_type_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateOperationTypeDto, UpdateOperationTypeDto};
use crate::domain::entity::OperationType;
use crate::infrastructure::persistence::OperationTypeRepository;

/// Application service for OperationType entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `operation_type_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct OperationTypeServiceCustom {
///     inner: Arc<OperationTypeService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type OperationTypeService = GenericCrudService<
    OperationType,
    CreateOperationTypeDto,
    UpdateOperationTypeDto,
    OperationTypeRepository,
>;

// <<< CUSTOM
// END CUSTOM
