//! Application service for PackageType entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `package_type_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePackageTypeDto, UpdatePackageTypeDto};
use crate::domain::entity::PackageType;
use crate::infrastructure::persistence::PackageTypeRepository;

/// Application service for PackageType entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `package_type_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PackageTypeServiceCustom {
///     inner: Arc<PackageTypeService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PackageTypeService = GenericCrudService<
    PackageType,
    CreatePackageTypeDto,
    UpdatePackageTypeDto,
    PackageTypeRepository,
>;

// <<< CUSTOM
// END CUSTOM
