//! Application service for PurchaseOrderItem entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `purchase_order_item_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePurchaseOrderItemDto, UpdatePurchaseOrderItemDto};
use crate::domain::entity::PurchaseOrderItem;
use crate::infrastructure::persistence::PurchaseOrderItemRepository;

/// Application service for PurchaseOrderItem entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `purchase_order_item_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PurchaseOrderItemServiceCustom {
///     inner: Arc<PurchaseOrderItemService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PurchaseOrderItemService = GenericCrudService<
    PurchaseOrderItem,
    CreatePurchaseOrderItemDto,
    UpdatePurchaseOrderItemDto,
    PurchaseOrderItemRepository,
>;

// <<< CUSTOM
// END CUSTOM
