//! Application service for StockReconciliation entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `stock_reconciliation_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateStockReconciliationDto, UpdateStockReconciliationDto};
use crate::domain::entity::StockReconciliation;
use crate::infrastructure::persistence::StockReconciliationRepository;

/// Application service for StockReconciliation entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `stock_reconciliation_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct StockReconciliationServiceCustom {
///     inner: Arc<StockReconciliationService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type StockReconciliationService = GenericCrudService<
    StockReconciliation,
    CreateStockReconciliationDto,
    UpdateStockReconciliationDto,
    StockReconciliationRepository,
>;

// <<< CUSTOM
// END CUSTOM
