//! Application service for Warehouse entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `warehouse_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateWarehouseDto, UpdateWarehouseDto};
use crate::domain::entity::Warehouse;
use crate::infrastructure::persistence::WarehouseRepository;

/// Application service for Warehouse entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `warehouse_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct WarehouseServiceCustom {
///     inner: Arc<WarehouseService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type WarehouseService = GenericCrudService<
    Warehouse,
    CreateWarehouseDto,
    UpdateWarehouseDto,
    WarehouseRepository,
>;

// <<< CUSTOM
// END CUSTOM
