-- ProductCategory Seed Data
-- Generated by backbone-schema
--
-- This file contains initial seed data for the product_categories table.
-- Customize this file to add your initial data.

-- INSERT INTO product_categories (
--     id,
--     provider_id,
--     code,
--     name,
--     description,
--     parent_id,
--     level,
--     path,
--     sort_order,
--     default_uom,
--     default_costing_method,
--     default_inventory_account_id,
--     default_cogs_account_id,
--     is_active,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO product_categories (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

