-- Route Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the inventory.routes table.
-- Customize this file to add your initial data.

-- INSERT INTO inventory.routes (
--     id,
--     name,
--     active,
--     sequence,
--     product_selectable,
--     product_categ_selectable,
--     warehouse_selectable,
--     company_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO inventory.routes (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

