-- Scrap Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the inventory.scraps table.
-- Customize this file to add your initial data.

-- INSERT INTO inventory.scraps (
--     id,
--     name,
--     state,
--     origin,
--     date_expected,
--     item_id,
--     scrap_qty,
--     location_id,
--     scrap_location_id,
--     lot_id,
--     package_id,
--     owner_id,
--     picking_id,
--     move_id,
--     scrap_reason_tag_ids,
--     company_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO inventory.scraps (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

