-- Stock Seed Data
-- Generated by backbone-schema
--
-- This file contains initial seed data for the stocks table.
-- Customize this file to add your initial data.

-- INSERT INTO stocks (
--     id,
--     provider_id,
--     product_id,
--     warehouse_id,
--     quantity_on_hand,
--     quantity_reserved,
--     quantity_on_order,
--     quantity_in_transit,
--     quantity_quarantine,
--     quantity_damaged,
--     currency,
--     unit_cost,
--     total_value,
--     data,
--     bin_location,
--     notes,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO stocks (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

