-- StockEntryItem Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the inventory.stock_entry_items table.
-- Customize this file to add your initial data.

-- INSERT INTO inventory.stock_entry_items (
--     id,
--     entry_id,
--     item_id,
--     quantity,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO inventory.stock_entry_items (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

