-- Migration: Create purchase_order_items table
-- Generated by backbone-schema

CREATE TABLE IF NOT EXISTS purchase_order_items (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    purchase_order_id UUID NOT NULL,
    provider_id UUID NOT NULL,
    line_number INTEGER NOT NULL,
    product_id UUID NOT NULL,
    description TEXT,
    uom unit_of_measure NOT NULL,
    quantity_ordered NUMERIC NOT NULL,
    base_uom unit_of_measure NOT NULL,
    base_quantity NUMERIC NOT NULL,
    currency TEXT NOT NULL DEFAULT 'IDR',
    unit_price NUMERIC NOT NULL,
    discount_percent NUMERIC NOT NULL DEFAULT 0,
    discount_amount NUMERIC NOT NULL DEFAULT 0,
    subtotal NUMERIC NOT NULL,
    tax_percent NUMERIC NOT NULL DEFAULT 0,
    tax_amount NUMERIC NOT NULL DEFAULT 0,
    total_amount NUMERIC NOT NULL,
    expected_date DATE,
    warehouse_id UUID,
    is_cancelled BOOLEAN NOT NULL DEFAULT FALSE,
    cancellation_reason TEXT,
    notes TEXT,
    data JSONB NOT NULL DEFAULT '{"sku":null,"product_name":null,"supplier_sku":null,"quantity_received":0,"quantity_outstanding":0,"quantity_rejected":0,"is_fully_received":false}'::jsonb,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_purchase_order_items_purchase_order_id_line_number ON purchase_order_items (purchase_order_id, line_number) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_purchase_order_items_purchase_order_id_product_id ON purchase_order_items (purchase_order_id, product_id);

CREATE INDEX IF NOT EXISTS idx_purchase_order_items_product_id_(data->>'is_fully_received') ON purchase_order_items (product_id, ((data->>'is_fully_received')));

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_purchase_order_items_metadata_gin ON purchase_order_items USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_purchase_order_items_metadata_deleted_at ON purchase_order_items ((metadata->>'deleted_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION purchase_order_items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS purchase_order_items_insert_audit ON purchase_order_items;
CREATE TRIGGER purchase_order_items_insert_audit BEFORE INSERT ON purchase_order_items
    FOR EACH ROW EXECUTE FUNCTION purchase_order_items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS purchase_order_items_update_audit ON purchase_order_items;
CREATE TRIGGER purchase_order_items_update_audit BEFORE UPDATE ON purchase_order_items
    FOR EACH ROW EXECUTE FUNCTION purchase_order_items_audit_timestamp();

