-- Migration: Create stock_adjustment_items table
-- Generated by backbone-schema

CREATE TABLE IF NOT EXISTS stock_adjustment_items (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    adjustment_id UUID NOT NULL,
    provider_id UUID NOT NULL,
    line_number INTEGER NOT NULL,
    product_id UUID NOT NULL,
    stock_id UUID NOT NULL,
    batch_id UUID,
    batch_number TEXT,
    expiry_date DATE,
    uom unit_of_measure NOT NULL,
    system_quantity NUMERIC NOT NULL,
    counted_quantity NUMERIC NOT NULL,
    variance_quantity NUMERIC NOT NULL,
    currency TEXT NOT NULL DEFAULT 'IDR',
    unit_cost NUMERIC NOT NULL,
    system_value NUMERIC NOT NULL,
    adjustment_value NUMERIC NOT NULL,
    variance_reason TEXT,
    bin_location TEXT,
    is_posted BOOLEAN NOT NULL DEFAULT FALSE,
    movement_id UUID,
    notes TEXT,
    data JSONB NOT NULL DEFAULT '{"sku":null,"product_name":null}'::jsonb,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_stock_adjustment_items_adjustment_id_line_number ON stock_adjustment_items (adjustment_id, line_number) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_stock_adjustment_items_adjustment_id_product_id ON stock_adjustment_items (adjustment_id, product_id);

CREATE INDEX IF NOT EXISTS idx_stock_adjustment_items_product_id ON stock_adjustment_items (product_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_stock_adjustment_items_metadata_gin ON stock_adjustment_items USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_stock_adjustment_items_metadata_deleted_at ON stock_adjustment_items ((metadata->>'deleted_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION stock_adjustment_items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS stock_adjustment_items_insert_audit ON stock_adjustment_items;
CREATE TRIGGER stock_adjustment_items_insert_audit BEFORE INSERT ON stock_adjustment_items
    FOR EACH ROW EXECUTE FUNCTION stock_adjustment_items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS stock_adjustment_items_update_audit ON stock_adjustment_items;
CREATE TRIGGER stock_adjustment_items_update_audit BEFORE UPDATE ON stock_adjustment_items
    FOR EACH ROW EXECUTE FUNCTION stock_adjustment_items_audit_timestamp();

