-- Migration: Create reordering_rules table
-- Generated by metaphor-schema

-- Create orderpoint_trigger enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'orderpoint_trigger') THEN
        CREATE TYPE orderpoint_trigger AS ENUM ('auto', 'manual');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS inventory;

CREATE TABLE IF NOT EXISTS inventory.reordering_rules (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    trigger orderpoint_trigger NOT NULL DEFAULT 'auto',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    snoozed_until DATE,
    item_id UUID NOT NULL,
    location_id UUID NOT NULL,
    warehouse_id UUID NOT NULL,
    company_id UUID NOT NULL,
    item_min_qty NUMERIC(18, 4) NOT NULL DEFAULT 0 CHECK (item_min_qty >= 0),
    item_max_qty NUMERIC(18, 4) NOT NULL DEFAULT 0 CHECK (item_max_qty >= 0),
    route_id UUID,
    qty_on_hand NUMERIC(18, 4) NOT NULL DEFAULT 0,
    qty_forecast NUMERIC(18, 4) NOT NULL DEFAULT 0,
    qty_to_order NUMERIC(18, 4) NOT NULL DEFAULT 0,
    qty_to_order_manual NUMERIC(18, 4) NOT NULL DEFAULT 0,
    lead_days NUMERIC(18, 4) NOT NULL DEFAULT 0,
    deadline_date DATE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_reordering_rules_item_id_location_id_company_id ON inventory.reordering_rules (item_id, location_id, company_id) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_reordering_rules_item_id ON inventory.reordering_rules (item_id);

CREATE INDEX IF NOT EXISTS idx_reordering_rules_location_id ON inventory.reordering_rules (location_id);

CREATE INDEX IF NOT EXISTS idx_reordering_rules_warehouse_id ON inventory.reordering_rules (warehouse_id);

CREATE INDEX IF NOT EXISTS idx_reordering_rules_company_id ON inventory.reordering_rules (company_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_reordering_rules_metadata_gin ON inventory.reordering_rules USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_reordering_rules_metadata_deleted_at ON inventory.reordering_rules ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_reordering_rules_metadata_created_at ON inventory.reordering_rules ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_reordering_rules_metadata_updated_at ON inventory.reordering_rules ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION inventory.reordering_rules_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS reordering_rules_insert_audit ON inventory.reordering_rules;
CREATE TRIGGER reordering_rules_insert_audit BEFORE INSERT ON inventory.reordering_rules
    FOR EACH ROW EXECUTE FUNCTION inventory.reordering_rules_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS reordering_rules_update_audit ON inventory.reordering_rules;
CREATE TRIGGER reordering_rules_update_audit BEFORE UPDATE ON inventory.reordering_rules
    FOR EACH ROW EXECUTE FUNCTION inventory.reordering_rules_audit_timestamp();
