-- Migration: Create stock_entry_items table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS inventory;

CREATE TABLE IF NOT EXISTS inventory.stock_entry_items (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    entry_id UUID NOT NULL,
    item_id UUID NOT NULL,
    quantity NUMERIC NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_stock_entry_items_entry_id ON inventory.stock_entry_items (entry_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_stock_entry_items_metadata_gin ON inventory.stock_entry_items USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_stock_entry_items_metadata_deleted_at ON inventory.stock_entry_items ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_stock_entry_items_metadata_created_at ON inventory.stock_entry_items ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_stock_entry_items_metadata_updated_at ON inventory.stock_entry_items ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION inventory.stock_entry_items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS stock_entry_items_insert_audit ON inventory.stock_entry_items;
CREATE TRIGGER stock_entry_items_insert_audit BEFORE INSERT ON inventory.stock_entry_items
    FOR EACH ROW EXECUTE FUNCTION inventory.stock_entry_items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS stock_entry_items_update_audit ON inventory.stock_entry_items;
CREATE TRIGGER stock_entry_items_update_audit BEFORE UPDATE ON inventory.stock_entry_items
    FOR EACH ROW EXECUTE FUNCTION inventory.stock_entry_items_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE inventory.stock_entry_items ADD CONSTRAINT fk_stock_entry_items_entry_id FOREIGN KEY (entry_id) REFERENCES inventory.stock_entries (id);
