-- Migration: Create locations table
-- Generated by metaphor-schema

-- Create location_usage enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'location_usage') THEN
        CREATE TYPE location_usage AS ENUM ('supplier', 'view', 'internal', 'customer', 'inventory', 'production', 'transit');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS inventory;

CREATE TABLE IF NOT EXISTS inventory.locations (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    complete_name TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    usage location_usage NOT NULL DEFAULT 'internal',
    location_id UUID,
    parent_path TEXT NOT NULL,
    barcode TEXT,
    company_id UUID,
    warehouse_id UUID,
    cyclic_inventory_frequency INTEGER NOT NULL DEFAULT 0,
    last_inventory_date DATE,
    next_inventory_date DATE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_locations_barcode_company_id ON inventory.locations (barcode, company_id) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS _parent_path_id_idx ON inventory.locations (parent_path, id);

CREATE INDEX IF NOT EXISTS idx_locations_location_id ON inventory.locations (location_id);

CREATE INDEX IF NOT EXISTS idx_locations_usage ON inventory.locations (usage);

CREATE INDEX IF NOT EXISTS idx_locations_warehouse_id ON inventory.locations (warehouse_id);

CREATE INDEX IF NOT EXISTS idx_locations_company_id ON inventory.locations (company_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_locations_metadata_gin ON inventory.locations USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_locations_metadata_deleted_at ON inventory.locations ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_locations_metadata_created_at ON inventory.locations ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_locations_metadata_updated_at ON inventory.locations ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION inventory.locations_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS locations_insert_audit ON inventory.locations;
CREATE TRIGGER locations_insert_audit BEFORE INSERT ON inventory.locations
    FOR EACH ROW EXECUTE FUNCTION inventory.locations_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS locations_update_audit ON inventory.locations;
CREATE TRIGGER locations_update_audit BEFORE UPDATE ON inventory.locations
    FOR EACH ROW EXECUTE FUNCTION inventory.locations_audit_timestamp();
