-- Migration: Create purchase_receipts table
-- Generated by metaphor-schema

-- Create doc_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'doc_status') THEN
        CREATE TYPE doc_status AS ENUM ('draft', 'submitted', 'cancelled');
    END IF;
END
$$;

-- Create gl_posting_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gl_posting_state') THEN
        CREATE TYPE gl_posting_state AS ENUM ('pending', 'posted', 'failed', 'not_applicable');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS inventory;

CREATE TABLE IF NOT EXISTS inventory.purchase_receipts (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    receipt_number TEXT NOT NULL,
    company_id UUID NOT NULL,
    branch_id UUID,
    supplier_id UUID NOT NULL,
    source_po_id UUID,
    warehouse_id UUID NOT NULL,
    posting_date DATE NOT NULL,
    currency TEXT NOT NULL DEFAULT 'IDR',
    total_value NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (total_value >= 0),
    inventory_account_id UUID NOT NULL,
    grir_account_id UUID NOT NULL,
    status doc_status NOT NULL DEFAULT 'draft',
    posting_state gl_posting_state NOT NULL DEFAULT 'pending',
    journal_id UUID,
    accounting_post_id UUID,
    posted_at TIMESTAMPTZ,
    notes TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_purchase_receipts_receipt_number ON inventory.purchase_receipts (receipt_number) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_purchase_receipts_company_id_supplier_id_status ON inventory.purchase_receipts (company_id, supplier_id, status);

CREATE INDEX IF NOT EXISTS idx_purchase_receipts_posting_state ON inventory.purchase_receipts (posting_state);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_purchase_receipts_metadata_gin ON inventory.purchase_receipts USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_purchase_receipts_metadata_deleted_at ON inventory.purchase_receipts ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_purchase_receipts_metadata_created_at ON inventory.purchase_receipts ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_purchase_receipts_metadata_updated_at ON inventory.purchase_receipts ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION inventory.purchase_receipts_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS purchase_receipts_insert_audit ON inventory.purchase_receipts;
CREATE TRIGGER purchase_receipts_insert_audit BEFORE INSERT ON inventory.purchase_receipts
    FOR EACH ROW EXECUTE FUNCTION inventory.purchase_receipts_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS purchase_receipts_update_audit ON inventory.purchase_receipts;
CREATE TRIGGER purchase_receipts_update_audit BEFORE UPDATE ON inventory.purchase_receipts
    FOR EACH ROW EXECUTE FUNCTION inventory.purchase_receipts_audit_timestamp();
