-- Migration: Create operation_types table
-- Generated by metaphor-schema

-- Create picking_code enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'picking_code') THEN
        CREATE TYPE picking_code AS ENUM ('incoming', 'outgoing', 'internal');
    END IF;
END
$$;

-- Create reservation_method enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'reservation_method') THEN
        CREATE TYPE reservation_method AS ENUM ('at_confirm', 'manual', 'by_date');
    END IF;
END
$$;

-- Create move_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'move_type') THEN
        CREATE TYPE move_type AS ENUM ('direct', 'one');
    END IF;
END
$$;

-- Create create_backorder enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'create_backorder') THEN
        CREATE TYPE create_backorder AS ENUM ('ask', 'always', 'never');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS inventory;

CREATE TABLE IF NOT EXISTS inventory.operation_types (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    sequence_code TEXT NOT NULL,
    code picking_code NOT NULL DEFAULT 'incoming',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    sequence INTEGER NOT NULL DEFAULT 10,
    company_id UUID,
    warehouse_id UUID,
    default_location_src_id UUID NOT NULL,
    default_location_dest_id UUID NOT NULL,
    reservation_method reservation_method NOT NULL DEFAULT 'at_confirm',
    reservation_days_before INTEGER,
    move_type move_type NOT NULL DEFAULT 'direct',
    create_backorder create_backorder NOT NULL DEFAULT 'ask',
    use_create_lots BOOLEAN NOT NULL DEFAULT TRUE,
    use_existing_lots BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_operation_types_company_id ON inventory.operation_types (company_id);

CREATE INDEX IF NOT EXISTS idx_operation_types_warehouse_id ON inventory.operation_types (warehouse_id);

CREATE INDEX IF NOT EXISTS idx_operation_types_code ON inventory.operation_types (code);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_operation_types_metadata_gin ON inventory.operation_types USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_operation_types_metadata_deleted_at ON inventory.operation_types ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_operation_types_metadata_created_at ON inventory.operation_types ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_operation_types_metadata_updated_at ON inventory.operation_types ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION inventory.operation_types_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS operation_types_insert_audit ON inventory.operation_types;
CREATE TRIGGER operation_types_insert_audit BEFORE INSERT ON inventory.operation_types
    FOR EACH ROW EXECUTE FUNCTION inventory.operation_types_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS operation_types_update_audit ON inventory.operation_types;
CREATE TRIGGER operation_types_update_audit BEFORE UPDATE ON inventory.operation_types
    FOR EACH ROW EXECUTE FUNCTION inventory.operation_types_audit_timestamp();
