-- Migration: Create bins table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS inventory;

CREATE TABLE IF NOT EXISTS inventory.bins (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    item_id UUID NOT NULL,
    warehouse_id UUID NOT NULL,
    actual_qty NUMERIC(18, 4) NOT NULL DEFAULT 0,
    reserved_qty NUMERIC(18, 4) NOT NULL DEFAULT 0 CHECK (reserved_qty >= 0),
    valuation_rate NUMERIC(18, 6) NOT NULL DEFAULT 0 CHECK (valuation_rate >= 0),
    stock_value NUMERIC(18, 2) NOT NULL DEFAULT 0,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_bins_company_id_item_id_warehouse_id ON inventory.bins (company_id, item_id, warehouse_id) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_bins_metadata_gin ON inventory.bins USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_bins_metadata_deleted_at ON inventory.bins ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_bins_metadata_created_at ON inventory.bins ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_bins_metadata_updated_at ON inventory.bins ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION inventory.bins_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS bins_insert_audit ON inventory.bins;
CREATE TRIGGER bins_insert_audit BEFORE INSERT ON inventory.bins
    FOR EACH ROW EXECUTE FUNCTION inventory.bins_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS bins_update_audit ON inventory.bins;
CREATE TRIGGER bins_update_audit BEFORE UPDATE ON inventory.bins
    FOR EACH ROW EXECUTE FUNCTION inventory.bins_audit_timestamp();
