-- Company RLS fence for inventory module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for inventory.delivery_notes
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE inventory.delivery_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.delivery_notes FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS delivery_notes_company_isolation ON inventory.delivery_notes;
CREATE POLICY delivery_notes_company_isolation ON inventory.delivery_notes
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for inventory.purchase_receipts
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE inventory.purchase_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.purchase_receipts FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS purchase_receipts_company_isolation ON inventory.purchase_receipts;
CREATE POLICY purchase_receipts_company_isolation ON inventory.purchase_receipts
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for inventory.stock_entries
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE inventory.stock_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.stock_entries FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS stock_entries_company_isolation ON inventory.stock_entries;
CREATE POLICY stock_entries_company_isolation ON inventory.stock_entries
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for inventory.stock_ledger_entries
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE inventory.stock_ledger_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.stock_ledger_entries FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS stock_ledger_entries_company_isolation ON inventory.stock_ledger_entries;
CREATE POLICY stock_ledger_entries_company_isolation ON inventory.stock_ledger_entries
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for inventory.bins
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE inventory.bins ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.bins FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS bins_company_isolation ON inventory.bins;
CREATE POLICY bins_company_isolation ON inventory.bins
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for inventory.stock_reconciliations
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE inventory.stock_reconciliations ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.stock_reconciliations FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS stock_reconciliations_company_isolation ON inventory.stock_reconciliations;
CREATE POLICY stock_reconciliations_company_isolation ON inventory.stock_reconciliations
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for inventory.warehouses
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE inventory.warehouses ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.warehouses FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS warehouses_company_isolation ON inventory.warehouses;
CREATE POLICY warehouses_company_isolation ON inventory.warehouses
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for inventory.stock_items
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE inventory.stock_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory.stock_items FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS stock_items_company_isolation ON inventory.stock_items;
CREATE POLICY stock_items_company_isolation ON inventory.stock_items
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

