//! Event handler trait for InventoryCompanySetting events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::InventoryCompanySettingEvent;

/// Event handler for InventoryCompanySetting events.
/// Implement this trait to react to InventoryCompanySetting lifecycle events.
pub trait InventoryCompanySettingEventHandler: EventHandler<InventoryCompanySettingEvent> {}
