//! Domain events
//!
//! Generated by backbone-schema. Do not edit manually.

pub mod goods_receipt_events;
pub mod goods_receipt_event_handlers;
pub mod goods_receipt_item_events;
pub mod goods_receipt_item_event_handlers;
pub mod product_category_events;
pub mod product_category_event_handlers;
pub mod product_events;
pub mod product_event_handlers;
pub mod purchase_order_events;
pub mod purchase_order_event_handlers;
pub mod purchase_order_item_events;
pub mod purchase_order_item_event_handlers;
pub mod stock_events;
pub mod stock_event_handlers;
pub mod stock_adjustment_events;
pub mod stock_adjustment_event_handlers;
pub mod stock_adjustment_item_events;
pub mod stock_adjustment_item_event_handlers;
pub mod stock_batch_events;
pub mod stock_batch_event_handlers;
pub mod stock_movement_events;
pub mod stock_movement_event_handlers;
pub mod stock_transfer_events;
pub mod stock_transfer_event_handlers;
pub mod stock_transfer_item_events;
pub mod stock_transfer_item_event_handlers;
pub mod warehouse_events;
pub mod warehouse_event_handlers;

pub use goods_receipt_events::{GoodsReceiptEvent, GoodsReceiptEventPublisher, NoopGoodsReceiptEventPublisher};
pub use goods_receipt_event_handlers::GoodsReceiptEventHandler;
pub use goods_receipt_item_events::{GoodsReceiptItemEvent, GoodsReceiptItemEventPublisher, NoopGoodsReceiptItemEventPublisher};
pub use goods_receipt_item_event_handlers::GoodsReceiptItemEventHandler;
pub use product_category_events::{ProductCategoryEvent, ProductCategoryEventPublisher, NoopProductCategoryEventPublisher};
pub use product_category_event_handlers::ProductCategoryEventHandler;
pub use product_events::{ProductEvent, ProductEventPublisher, NoopProductEventPublisher};
pub use product_event_handlers::ProductEventHandler;
pub use purchase_order_events::{PurchaseOrderEvent, PurchaseOrderEventPublisher, NoopPurchaseOrderEventPublisher};
pub use purchase_order_event_handlers::PurchaseOrderEventHandler;
pub use purchase_order_item_events::{PurchaseOrderItemEvent, PurchaseOrderItemEventPublisher, NoopPurchaseOrderItemEventPublisher};
pub use purchase_order_item_event_handlers::PurchaseOrderItemEventHandler;
pub use stock_events::{StockEvent, StockEventPublisher, NoopStockEventPublisher};
pub use stock_event_handlers::StockEventHandler;
pub use stock_adjustment_events::{StockAdjustmentEvent, StockAdjustmentEventPublisher, NoopStockAdjustmentEventPublisher};
pub use stock_adjustment_event_handlers::StockAdjustmentEventHandler;
pub use stock_adjustment_item_events::{StockAdjustmentItemEvent, StockAdjustmentItemEventPublisher, NoopStockAdjustmentItemEventPublisher};
pub use stock_adjustment_item_event_handlers::StockAdjustmentItemEventHandler;
pub use stock_batch_events::{StockBatchEvent, StockBatchEventPublisher, NoopStockBatchEventPublisher};
pub use stock_batch_event_handlers::StockBatchEventHandler;
pub use stock_movement_events::{StockMovementEvent, StockMovementEventPublisher, NoopStockMovementEventPublisher};
pub use stock_movement_event_handlers::StockMovementEventHandler;
pub use stock_transfer_events::{StockTransferEvent, StockTransferEventPublisher, NoopStockTransferEventPublisher};
pub use stock_transfer_event_handlers::StockTransferEventHandler;
pub use stock_transfer_item_events::{StockTransferItemEvent, StockTransferItemEventPublisher, NoopStockTransferItemEventPublisher};
pub use stock_transfer_item_event_handlers::StockTransferItemEventHandler;
pub use warehouse_events::{WarehouseEvent, WarehouseEventPublisher, NoopWarehouseEventPublisher};
pub use warehouse_event_handlers::WarehouseEventHandler;

// <<< CUSTOM
// END CUSTOM
