//! Event handler trait for PurchaseReceiptItem events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PurchaseReceiptItemEvent;

/// Event handler for PurchaseReceiptItem events.
/// Implement this trait to react to PurchaseReceiptItem lifecycle events.
pub trait PurchaseReceiptItemEventHandler: EventHandler<PurchaseReceiptItemEvent> {}
