//! Domain events for Quant entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Quant;

/// Domain events for Quant — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Quant>)` variant.
pub type QuantEvent = CrudEvent<Quant>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Quant events.
pub type QuantEventPublisher = Arc<dyn CrudEventPublisher<Quant> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopQuantEventPublisher = NoOpCrudEventPublisher<Quant>;
