//! Domain events for StockAdjustment entity
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::StockAdjustment;

/// Domain events for StockAdjustment — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<StockAdjustment>)` variant.
pub type StockAdjustmentEvent = CrudEvent<StockAdjustment>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for StockAdjustment events.
pub type StockAdjustmentEventPublisher = Arc<dyn CrudEventPublisher<StockAdjustment> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopStockAdjustmentEventPublisher = NoOpCrudEventPublisher<StockAdjustment>;
