//! Domain events for Stock entity
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Stock;

/// Domain events for Stock — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Stock>)` variant.
pub type StockEvent = CrudEvent<Stock>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Stock events.
pub type StockEventPublisher = Arc<dyn CrudEventPublisher<Stock> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopStockEventPublisher = NoOpCrudEventPublisher<Stock>;
