//! Domain events for StockAdjustmentItem entity
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::StockAdjustmentItem;

/// Domain events for StockAdjustmentItem — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<StockAdjustmentItem>)` variant.
pub type StockAdjustmentItemEvent = CrudEvent<StockAdjustmentItem>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for StockAdjustmentItem events.
pub type StockAdjustmentItemEventPublisher = Arc<dyn CrudEventPublisher<StockAdjustmentItem> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopStockAdjustmentItemEventPublisher = NoOpCrudEventPublisher<StockAdjustmentItem>;
