//! Event handler trait for StockTransferItem events
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::StockTransferItemEvent;

/// Event handler for StockTransferItem events.
/// Implement this trait to react to StockTransferItem lifecycle events.
pub trait StockTransferItemEventHandler: EventHandler<StockTransferItemEvent> {}
