//! Domain events for Transfer entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Transfer;

/// Domain events for Transfer — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Transfer>)` variant.
pub type TransferEvent = CrudEvent<Transfer>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Transfer events.
pub type TransferEventPublisher = Arc<dyn CrudEventPublisher<Transfer> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopTransferEventPublisher = NoOpCrudEventPublisher<Transfer>;
