//! Event handler trait for Transfer events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::TransferEvent;

/// Event handler for Transfer events.
/// Implement this trait to react to Transfer lifecycle events.
pub trait TransferEventHandler: EventHandler<TransferEvent> {}
