//! Event handler trait for Warehouse events
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::WarehouseEvent;

/// Event handler for Warehouse events.
/// Implement this trait to react to Warehouse lifecycle events.
pub trait WarehouseEventHandler: EventHandler<WarehouseEvent> {}
