//! Inventory Event Subscriptions
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Cross-module event subscriptions. Each entity subscriber is a type alias
//! over `GenericEventSubscriber` from backbone-messaging.

pub mod handlers;
pub mod registry;

pub use handlers::*;
pub use registry::SubscriptionRegistry;

pub use handlers::GoodsReceiptEventSubscriber;
pub use handlers::GoodsReceiptItemEventSubscriber;
pub use handlers::ProductCategoryEventSubscriber;
pub use handlers::ProductEventSubscriber;
pub use handlers::PurchaseOrderEventSubscriber;
pub use handlers::PurchaseOrderItemEventSubscriber;
pub use handlers::StockEventSubscriber;
pub use handlers::StockAdjustmentEventSubscriber;
pub use handlers::StockAdjustmentItemEventSubscriber;
pub use handlers::StockBatchEventSubscriber;
pub use handlers::StockMovementEventSubscriber;
pub use handlers::StockTransferEventSubscriber;
pub use handlers::StockTransferItemEventSubscriber;
pub use handlers::WarehouseEventSubscriber;
