//! Database seeders for the inventory module
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This module provides seed data for initial database setup.
//! Seeders can be run via the seeder binary or CLI.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

mod goods_receipt_seeder;
mod goods_receipt_item_seeder;
mod product_category_seeder;
mod product_seeder;
mod purchase_order_seeder;
mod purchase_order_item_seeder;
mod stock_seeder;
mod stock_adjustment_seeder;
mod stock_adjustment_item_seeder;
mod stock_batch_seeder;
mod stock_movement_seeder;
mod stock_transfer_seeder;
mod stock_transfer_item_seeder;
mod warehouse_seeder;

pub use goods_receipt_seeder::SeedGoodsReceiptSeeder;
pub use goods_receipt_item_seeder::SeedGoodsReceiptItemSeeder;
pub use product_category_seeder::SeedProductCategorySeeder;
pub use product_seeder::SeedProductSeeder;
pub use purchase_order_seeder::SeedPurchaseOrderSeeder;
pub use purchase_order_item_seeder::SeedPurchaseOrderItemSeeder;
pub use stock_seeder::SeedStockSeeder;
pub use stock_adjustment_seeder::SeedStockAdjustmentSeeder;
pub use stock_adjustment_item_seeder::SeedStockAdjustmentItemSeeder;
pub use stock_batch_seeder::SeedStockBatchSeeder;
pub use stock_movement_seeder::SeedStockMovementSeeder;
pub use stock_transfer_seeder::SeedStockTransferSeeder;
pub use stock_transfer_item_seeder::SeedStockTransferItemSeeder;
pub use warehouse_seeder::SeedWarehouseSeeder;

// ============================================================================
// SEEDER TRAIT
// ============================================================================

/// Trait for database seeders
#[async_trait]
pub trait Seeder {
    /// Get the name of this seeder
    fn name(&self) -> &'static str;

    /// Get the order in which this seeder should run
    fn order(&self) -> i32;

    /// Check if this seeder should run (e.g., check if data already exists)
    async fn should_run(&self, pool: &PgPool) -> Result<bool>;

    /// Run the seeder
    async fn run(&self, pool: &PgPool) -> Result<()>;

    /// Rollback the seeder (optional)
    async fn rollback(&self, _pool: &PgPool) -> Result<()> {
        Ok(())
    }
}

// ============================================================================
// SEEDER TYPE
// ============================================================================

/// Type of seeder
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SeederType {
    /// Reference data (required for application to function)
    Reference,
    /// Initial production data
    Production,
    /// Development/testing data
    Development,
    /// Test data (for automated tests)
    Test,
}

// ============================================================================
// CUSTOM SEEDERS
// ============================================================================

// <<< CUSTOM SEEDERS START >>>
// Add custom seeders here
// <<< CUSTOM SEEDERS END >>>

