//! StockMovement seeder
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Seeds initial StockMovement data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// STOCKMOVEMENT SEEDER
// ============================================================================

/// Seeder for stock_movement
pub struct SeedStockMovementSeeder;

impl SeedStockMovementSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedStockMovementSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedStockMovementSeeder {
    fn name(&self) -> &'static str {
        "SeedStockMovementSeeder"
    }

    fn order(&self) -> i32 {
        10
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if stock_movements table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM stock_movements")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/stock_movement_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM stock_movements")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

