//! StockEntry seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial StockEntry data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// STOCKENTRY SEEDER
// ============================================================================

/// Seeder for stock_entry
pub struct SeedStockEntrySeeder;

impl SeedStockEntrySeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedStockEntrySeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedStockEntrySeeder {
    fn name(&self) -> &'static str {
        "SeedStockEntrySeeder"
    }

    fn order(&self) -> i32 {
        5
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if inventory.stock_entries table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM inventory.stock_entries")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/stock_entry_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM inventory.stock_entries")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

