//! Repository trait for PurchaseOrderItem aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PurchaseOrderItem aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{PurchaseOrderItem, UnitOfMeasure};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PurchaseOrderItemPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PurchaseOrderItemPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PurchaseOrderItemPaginatedResult {
    pub data: Vec<PurchaseOrderItem>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PurchaseOrderItemFilter {
    pub purchase_order_id: Option<Uuid>,
    pub provider_id: Option<Uuid>,
    pub product_id: Option<Uuid>,
    pub description: Option<String>,
    pub uom: Option<UnitOfMeasure>,
    pub base_uom: Option<UnitOfMeasure>,
    pub currency: Option<String>,
    pub warehouse_id: Option<Uuid>,
    pub is_cancelled: Option<bool>,
    pub cancellation_reason: Option<String>,
    pub notes: Option<String>,
}

impl PurchaseOrderItemFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.purchase_order_id.is_some() || self.provider_id.is_some() || self.product_id.is_some() || self.description.is_some() || self.uom.is_some() || self.base_uom.is_some() || self.currency.is_some() || self.warehouse_id.is_some() || self.is_cancelled.is_some() || self.cancellation_reason.is_some() || self.notes.is_some()
    }
}

/// Repository trait for PurchaseOrderItem aggregate
///
/// This trait defines the persistence contract for PurchaseOrderItem entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PurchaseOrderItemRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new purchase_order_item entity
    async fn save(&self, entity: &PurchaseOrderItem) -> Result<PurchaseOrderItem>;

    /// Find purchase_order_item by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PurchaseOrderItem>>;

    /// Find all purchase_order_item entities
    async fn find_all(&self) -> Result<Vec<PurchaseOrderItem>>;

    /// Update purchase_order_item by ID
    async fn update(&self, id: &str, entity: &PurchaseOrderItem) -> Result<Option<PurchaseOrderItem>>;

    /// Delete purchase_order_item by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List purchase_order_item with pagination
    async fn list(&self, params: PurchaseOrderItemPaginationParams) -> Result<PurchaseOrderItemPaginatedResult>;

    /// List purchase_order_item with pagination and filters
    async fn list_with_filters(&self, params: PurchaseOrderItemPaginationParams, filters: PurchaseOrderItemFilter) -> Result<PurchaseOrderItemPaginatedResult>;

    /// Count all purchase_order_item entities
    async fn count(&self) -> Result<u64>;

    /// Count purchase_order_item entities matching filters
    async fn count_with_filters(&self, filters: PurchaseOrderItemFilter) -> Result<u64>;

    /// Check if purchase_order_item exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete purchase_order_item by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted purchase_order_item by ID
    async fn restore(&self, id: &str) -> Result<Option<PurchaseOrderItem>>;

    /// List soft-deleted purchase_order_item entities
    async fn list_deleted(&self, params: PurchaseOrderItemPaginationParams) -> Result<PurchaseOrderItemPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save purchase_order_item entities
    async fn bulk_save(&self, entities: &[PurchaseOrderItem]) -> Result<Vec<PurchaseOrderItem>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
