//! Repository trait for StockReconciliationItem aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the StockReconciliationItem aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::StockReconciliationItem;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct StockReconciliationItemPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl StockReconciliationItemPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct StockReconciliationItemPaginatedResult {
    pub data: Vec<StockReconciliationItem>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct StockReconciliationItemFilter {
    pub reconciliation_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
}

impl StockReconciliationItemFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.reconciliation_id.is_some() || self.item_id.is_some()
    }
}

/// Repository trait for StockReconciliationItem aggregate
///
/// This trait defines the persistence contract for StockReconciliationItem entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait StockReconciliationItemRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new stock_reconciliation_item entity
    async fn save(&self, entity: &StockReconciliationItem) -> Result<StockReconciliationItem>;

    /// Find stock_reconciliation_item by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<StockReconciliationItem>>;

    /// Find all stock_reconciliation_item entities
    async fn find_all(&self) -> Result<Vec<StockReconciliationItem>>;

    /// Update stock_reconciliation_item by ID
    async fn update(&self, id: &str, entity: &StockReconciliationItem) -> Result<Option<StockReconciliationItem>>;

    /// Delete stock_reconciliation_item by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List stock_reconciliation_item with pagination
    async fn list(&self, params: StockReconciliationItemPaginationParams) -> Result<StockReconciliationItemPaginatedResult>;

    /// List stock_reconciliation_item with pagination and filters
    async fn list_with_filters(&self, params: StockReconciliationItemPaginationParams, filters: StockReconciliationItemFilter) -> Result<StockReconciliationItemPaginatedResult>;

    /// Count all stock_reconciliation_item entities
    async fn count(&self) -> Result<u64>;

    /// Count stock_reconciliation_item entities matching filters
    async fn count_with_filters(&self, filters: StockReconciliationItemFilter) -> Result<u64>;

    /// Check if stock_reconciliation_item exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete stock_reconciliation_item by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted stock_reconciliation_item by ID
    async fn restore(&self, id: &str) -> Result<Option<StockReconciliationItem>>;

    /// List soft-deleted stock_reconciliation_item entities
    async fn list_deleted(&self, params: StockReconciliationItemPaginationParams) -> Result<StockReconciliationItemPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save stock_reconciliation_item entities
    async fn bulk_save(&self, entities: &[StockReconciliationItem]) -> Result<Vec<StockReconciliationItem>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
