//! Repository trait for StockMovement aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the StockMovement aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{StockMovement, MovementReason, MovementStatus, MovementType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct StockMovementPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl StockMovementPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct StockMovementPaginatedResult {
    pub data: Vec<StockMovement>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct StockMovementFilter {
    pub provider_id: Option<Uuid>,
    pub movement_number: Option<String>,
    pub movement_type: Option<MovementType>,
    pub movement_reason: Option<MovementReason>,
    pub product_id: Option<Uuid>,
    pub warehouse_id: Option<Uuid>,
    pub from_location: Option<String>,
    pub to_location: Option<String>,
    pub uom: Option<String>,
    pub batch_id: Option<Uuid>,
    pub batch_number: Option<String>,
    pub currency: Option<String>,
    pub source_type: Option<String>,
    pub source_id: Option<Uuid>,
    pub source_number: Option<String>,
    pub status: Option<MovementStatus>,
    pub performed_by: Option<Uuid>,
    pub reason_detail: Option<String>,
    pub notes: Option<String>,
}

impl StockMovementFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.provider_id.is_some() || self.movement_number.is_some() || self.movement_type.is_some() || self.movement_reason.is_some() || self.product_id.is_some() || self.warehouse_id.is_some() || self.from_location.is_some() || self.to_location.is_some() || self.uom.is_some() || self.batch_id.is_some() || self.batch_number.is_some() || self.currency.is_some() || self.source_type.is_some() || self.source_id.is_some() || self.source_number.is_some() || self.status.is_some() || self.performed_by.is_some() || self.reason_detail.is_some() || self.notes.is_some()
    }
}

/// Repository trait for StockMovement aggregate
///
/// This trait defines the persistence contract for StockMovement entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait StockMovementRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new stock_movement entity
    async fn save(&self, entity: &StockMovement) -> Result<StockMovement>;

    /// Find stock_movement by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<StockMovement>>;

    /// Find all stock_movement entities
    async fn find_all(&self) -> Result<Vec<StockMovement>>;

    /// Update stock_movement by ID
    async fn update(&self, id: &str, entity: &StockMovement) -> Result<Option<StockMovement>>;

    /// Delete stock_movement by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List stock_movement with pagination
    async fn list(&self, params: StockMovementPaginationParams) -> Result<StockMovementPaginatedResult>;

    /// List stock_movement with pagination and filters
    async fn list_with_filters(&self, params: StockMovementPaginationParams, filters: StockMovementFilter) -> Result<StockMovementPaginatedResult>;

    /// Count all stock_movement entities
    async fn count(&self) -> Result<u64>;

    /// Count stock_movement entities matching filters
    async fn count_with_filters(&self, filters: StockMovementFilter) -> Result<u64>;

    /// Check if stock_movement exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete stock_movement by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted stock_movement by ID
    async fn restore(&self, id: &str) -> Result<Option<StockMovement>>;

    /// List soft-deleted stock_movement entities
    async fn list_deleted(&self, params: StockMovementPaginationParams) -> Result<StockMovementPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save stock_movement entities
    async fn bulk_save(&self, entities: &[StockMovement]) -> Result<Vec<StockMovement>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
