//! Repository trait for StockEntry aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the StockEntry aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{StockEntry, DocStatus, GlPostingState, StockEntryType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct StockEntryPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl StockEntryPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct StockEntryPaginatedResult {
    pub data: Vec<StockEntry>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct StockEntryFilter {
    pub entry_number: Option<String>,
    pub company_id: Option<Uuid>,
    pub stock_entry_type: Option<StockEntryType>,
    pub from_warehouse_id: Option<Uuid>,
    pub to_warehouse_id: Option<Uuid>,
    pub status: Option<DocStatus>,
    pub posting_state: Option<GlPostingState>,
    pub notes: Option<String>,
}

impl StockEntryFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.entry_number.is_some() || self.company_id.is_some() || self.stock_entry_type.is_some() || self.from_warehouse_id.is_some() || self.to_warehouse_id.is_some() || self.status.is_some() || self.posting_state.is_some() || self.notes.is_some()
    }
}

/// Repository trait for StockEntry aggregate
///
/// This trait defines the persistence contract for StockEntry entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait StockEntryRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new stock_entry entity
    async fn save(&self, entity: &StockEntry) -> Result<StockEntry>;

    /// Find stock_entry by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<StockEntry>>;

    /// Find all stock_entry entities
    async fn find_all(&self) -> Result<Vec<StockEntry>>;

    /// Update stock_entry by ID
    async fn update(&self, id: &str, entity: &StockEntry) -> Result<Option<StockEntry>>;

    /// Delete stock_entry by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List stock_entry with pagination
    async fn list(&self, params: StockEntryPaginationParams) -> Result<StockEntryPaginatedResult>;

    /// List stock_entry with pagination and filters
    async fn list_with_filters(&self, params: StockEntryPaginationParams, filters: StockEntryFilter) -> Result<StockEntryPaginatedResult>;

    /// Count all stock_entry entities
    async fn count(&self) -> Result<u64>;

    /// Count stock_entry entities matching filters
    async fn count_with_filters(&self, filters: StockEntryFilter) -> Result<u64>;

    /// Check if stock_entry exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete stock_entry by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted stock_entry by ID
    async fn restore(&self, id: &str) -> Result<Option<StockEntry>>;

    /// List soft-deleted stock_entry entities
    async fn list_deleted(&self, params: StockEntryPaginationParams) -> Result<StockEntryPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save stock_entry entities
    async fn bulk_save(&self, entities: &[StockEntry]) -> Result<Vec<StockEntry>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
