//! Repository trait for StockBatch aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the StockBatch aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{StockBatch, BatchStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct StockBatchPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl StockBatchPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct StockBatchPaginatedResult {
    pub data: Vec<StockBatch>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct StockBatchFilter {
    pub provider_id: Option<Uuid>,
    pub product_id: Option<Uuid>,
    pub warehouse_id: Option<Uuid>,
    pub batch_number: Option<String>,
    pub supplier_batch: Option<String>,
    pub uom: Option<String>,
    pub currency: Option<String>,
    pub source_type: Option<String>,
    pub source_document: Option<String>,
    pub goods_receipt_id: Option<Uuid>,
    pub supplier_id: Option<Uuid>,
    pub bin_location: Option<String>,
    pub status: Option<BatchStatus>,
    pub is_active: Option<bool>,
    pub notes: Option<String>,
}

impl StockBatchFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.provider_id.is_some() || self.product_id.is_some() || self.warehouse_id.is_some() || self.batch_number.is_some() || self.supplier_batch.is_some() || self.uom.is_some() || self.currency.is_some() || self.source_type.is_some() || self.source_document.is_some() || self.goods_receipt_id.is_some() || self.supplier_id.is_some() || self.bin_location.is_some() || self.status.is_some() || self.is_active.is_some() || self.notes.is_some()
    }
}

/// Repository trait for StockBatch aggregate
///
/// This trait defines the persistence contract for StockBatch entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait StockBatchRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new stock_batch entity
    async fn save(&self, entity: &StockBatch) -> Result<StockBatch>;

    /// Find stock_batch by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<StockBatch>>;

    /// Find all stock_batch entities
    async fn find_all(&self) -> Result<Vec<StockBatch>>;

    /// Update stock_batch by ID
    async fn update(&self, id: &str, entity: &StockBatch) -> Result<Option<StockBatch>>;

    /// Delete stock_batch by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List stock_batch with pagination
    async fn list(&self, params: StockBatchPaginationParams) -> Result<StockBatchPaginatedResult>;

    /// List stock_batch with pagination and filters
    async fn list_with_filters(&self, params: StockBatchPaginationParams, filters: StockBatchFilter) -> Result<StockBatchPaginatedResult>;

    /// Count all stock_batch entities
    async fn count(&self) -> Result<u64>;

    /// Count stock_batch entities matching filters
    async fn count_with_filters(&self, filters: StockBatchFilter) -> Result<u64>;

    /// Check if stock_batch exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete stock_batch by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted stock_batch by ID
    async fn restore(&self, id: &str) -> Result<Option<StockBatch>>;

    /// List soft-deleted stock_batch entities
    async fn list_deleted(&self, params: StockBatchPaginationParams) -> Result<StockBatchPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save stock_batch entities
    async fn bulk_save(&self, entities: &[StockBatch]) -> Result<Vec<StockBatch>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
