//! Repository trait for Transfer aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Transfer aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Transfer, MoveType, Priority, TransferState};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TransferPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl TransferPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct TransferPaginatedResult {
    pub data: Vec<Transfer>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TransferFilter {
    pub name: Option<String>,
    pub origin: Option<String>,
    pub note: Option<String>,
    pub priority: Option<Priority>,
    pub picking_type_id: Option<Uuid>,
    pub location_id: Option<Uuid>,
    pub location_dest_id: Option<Uuid>,
    pub partner_id: Option<Uuid>,
    pub company_id: Option<Uuid>,
    pub move_type: Option<MoveType>,
    pub state: Option<TransferState>,
    pub is_locked: Option<bool>,
    pub backorder_id: Option<Uuid>,
    pub return_id: Option<Uuid>,
    pub batch_id: Option<Uuid>,
}

impl TransferFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.origin.is_some() || self.note.is_some() || self.priority.is_some() || self.picking_type_id.is_some() || self.location_id.is_some() || self.location_dest_id.is_some() || self.partner_id.is_some() || self.company_id.is_some() || self.move_type.is_some() || self.state.is_some() || self.is_locked.is_some() || self.backorder_id.is_some() || self.return_id.is_some() || self.batch_id.is_some()
    }
}

/// Repository trait for Transfer aggregate
///
/// This trait defines the persistence contract for Transfer entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait TransferRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new transfer entity
    async fn save(&self, entity: &Transfer) -> Result<Transfer>;

    /// Find transfer by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Transfer>>;

    /// Find all transfer entities
    async fn find_all(&self) -> Result<Vec<Transfer>>;

    /// Update transfer by ID
    async fn update(&self, id: &str, entity: &Transfer) -> Result<Option<Transfer>>;

    /// Delete transfer by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List transfer with pagination
    async fn list(&self, params: TransferPaginationParams) -> Result<TransferPaginatedResult>;

    /// List transfer with pagination and filters
    async fn list_with_filters(&self, params: TransferPaginationParams, filters: TransferFilter) -> Result<TransferPaginatedResult>;

    /// Count all transfer entities
    async fn count(&self) -> Result<u64>;

    /// Count transfer entities matching filters
    async fn count_with_filters(&self, filters: TransferFilter) -> Result<u64>;

    /// Check if transfer exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete transfer by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted transfer by ID
    async fn restore(&self, id: &str) -> Result<Option<Transfer>>;

    /// List soft-deleted transfer entities
    async fn list_deleted(&self, params: TransferPaginationParams) -> Result<TransferPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save transfer entities
    async fn bulk_save(&self, entities: &[Transfer]) -> Result<Vec<Transfer>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
