//! Repository for PackageType entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PackageType, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::PackageType;

/// Table name for PackageType entities
pub const TABLE_NAME: &str = "inventory.package_types";

/// Repository for PackageType entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PackageTypeRepository(
    backbone_orm::GenericCrudRepository<PackageType, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PackageTypeRepository {
    type Target = backbone_orm::GenericCrudRepository<PackageType, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PackageTypeRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PackageTypeRepository, PackageType, soft_delete);
