//! Repository for PurchaseReceipt entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PurchaseReceipt, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::PurchaseReceipt;

/// Table name for PurchaseReceipt entities
pub const TABLE_NAME: &str = "inventory.purchase_receipts";

/// Repository for PurchaseReceipt entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PurchaseReceiptRepository(
    backbone_orm::GenericCrudRepository<PurchaseReceipt, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PurchaseReceiptRepository {
    type Target = backbone_orm::GenericCrudRepository<PurchaseReceipt, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PurchaseReceiptRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PurchaseReceiptRepository, PurchaseReceipt, soft_delete);
