//! Repository for StockBatch entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<StockBatch, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::StockBatch;

/// Table name for StockBatch entities
pub const TABLE_NAME: &str = "stock_batches";

/// Repository for StockBatch entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct StockBatchRepository(
    backbone_orm::GenericCrudRepository<StockBatch, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for StockBatchRepository {
    type Target = backbone_orm::GenericCrudRepository<StockBatch, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl StockBatchRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(StockBatchRepository, StockBatch, soft_delete);
