//! Repository for StorageCategoryCapacity entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<StorageCategoryCapacity, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::StorageCategoryCapacity;

/// Table name for StorageCategoryCapacity entities
pub const TABLE_NAME: &str = "inventory.storage_category_capacities";

/// Repository for StorageCategoryCapacity entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct StorageCategoryCapacityRepository(
    backbone_orm::GenericCrudRepository<StorageCategoryCapacity, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for StorageCategoryCapacityRepository {
    type Target = backbone_orm::GenericCrudRepository<StorageCategoryCapacity, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl StorageCategoryCapacityRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(StorageCategoryCapacityRepository, StorageCategoryCapacity, soft_delete);
