//! Validator for LandedCostLine entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<LandedCostLine>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::LandedCostLine;

/// Validator type alias for LandedCostLine entities.
pub type LandedCostLineValidator = EntityValidator<LandedCostLine>;

/// Build a validator for LandedCostLine with all schema-defined field rules.
pub fn landed_cost_line_validator() -> LandedCostLineValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &LandedCostLine| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
