//! Validator for Product entity
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Product>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString, RequiredUuid};
use crate::domain::entity::Product;

/// Validator type alias for Product entities.
pub type ProductValidator = EntityValidator<Product>;

/// Build a validator for Product with all schema-defined field rules.
pub fn product_validator() -> ProductValidator {
    EntityValidator::new()
        .rule(RequiredString::new("sku", |e: &Product| &e.sku))
        .rule(OptionalNotBlank::new("barcode", |e: &Product| e.barcode.as_deref()))
        .rule(RequiredString::new("name", |e: &Product| &e.name))
        .rule(OptionalNotBlank::new("description", |e: &Product| e.description.as_deref()))
        .rule(RequiredUuid::new("category_id", |e: &Product| &e.category_id))
        .rule(OptionalNotBlank::new("brand", |e: &Product| e.brand.as_deref()))
        .rule(OptionalNotBlank::new("manufacturer", |e: &Product| e.manufacturer.as_deref()))
        .rule(NonNegative::new("weight_kg", |e: &Product| e.weight_kg))
        .rule(NonNegative::new("volume_liter", |e: &Product| e.volume_liter))
        .rule(NonNegative::new("standard_cost", |e: &Product| e.standard_cost))
        .rule(NonNegative::new("last_purchase_cost", |e: &Product| e.last_purchase_cost))
        .rule(NonNegative::new("average_cost", |e: &Product| e.average_cost))
        .rule(RequiredString::new("currency", |e: &Product| &e.currency))
        .rule(NonNegative::new("shelf_life_days", |e: &Product| e.shelf_life_days))
        .rule(NonNegative::new("expiry_warning_days", |e: &Product| e.expiry_warning_days))
        .rule(NonNegative::new("min_stock", |e: &Product| e.min_stock))
        .rule(NonNegative::new("max_stock", |e: &Product| e.max_stock))
        .rule(NonNegative::new("reorder_quantity", |e: &Product| e.reorder_quantity))
        .rule(NonNegative::new("safety_stock", |e: &Product| e.safety_stock))
        .rule(NonNegative::new("lead_time_days", |e: &Product| e.lead_time_days))
        .rule(NonNegative::new("usage_per_kg", |e: &Product| e.usage_per_kg))
        .rule(NonNegative::new("usage_per_order", |e: &Product| e.usage_per_order))
        .rule(OptionalNotBlank::new("storage_conditions", |e: &Product| e.storage_conditions.as_deref()))
        .rule(OptionalNotBlank::new("image_url", |e: &Product| e.image_url.as_deref()))
        .rule(OptionalNotBlank::new("notes", |e: &Product| e.notes.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
