//! Validator for StockAdjustmentItem entity
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<StockAdjustmentItem>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString, RequiredUuid};
use crate::domain::entity::StockAdjustmentItem;

/// Validator type alias for StockAdjustmentItem entities.
pub type StockAdjustmentItemValidator = EntityValidator<StockAdjustmentItem>;

/// Build a validator for StockAdjustmentItem with all schema-defined field rules.
pub fn stock_adjustment_item_validator() -> StockAdjustmentItemValidator {
    EntityValidator::new()
        .rule(RequiredUuid::new("adjustment_id", |e: &StockAdjustmentItem| &e.adjustment_id))
        .rule(RequiredUuid::new("provider_id", |e: &StockAdjustmentItem| &e.provider_id))
        .rule(RequiredUuid::new("product_id", |e: &StockAdjustmentItem| &e.product_id))
        .rule(RequiredUuid::new("stock_id", |e: &StockAdjustmentItem| &e.stock_id))
        .rule(OptionalNotBlank::new("batch_number", |e: &StockAdjustmentItem| e.batch_number.as_deref()))
        .rule(RequiredString::new("currency", |e: &StockAdjustmentItem| &e.currency))
        .rule(NonNegative::new("unit_cost", |e: &StockAdjustmentItem| e.unit_cost))
        .rule(OptionalNotBlank::new("variance_reason", |e: &StockAdjustmentItem| e.variance_reason.as_deref()))
        .rule(OptionalNotBlank::new("bin_location", |e: &StockAdjustmentItem| e.bin_location.as_deref()))
        .rule(OptionalNotBlank::new("notes", |e: &StockAdjustmentItem| e.notes.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
