//! Validator for StockTransfer entity
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<StockTransfer>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString, RequiredUuid};
use crate::domain::entity::StockTransfer;

/// Validator type alias for StockTransfer entities.
pub type StockTransferValidator = EntityValidator<StockTransfer>;

/// Build a validator for StockTransfer with all schema-defined field rules.
pub fn stock_transfer_validator() -> StockTransferValidator {
    EntityValidator::new()
        .rule(RequiredUuid::new("provider_id", |e: &StockTransfer| &e.provider_id))
        .rule(RequiredString::new("transfer_number", |e: &StockTransfer| &e.transfer_number))
        .rule(RequiredUuid::new("from_warehouse_id", |e: &StockTransfer| &e.from_warehouse_id))
        .rule(OptionalNotBlank::new("from_location", |e: &StockTransfer| e.from_location.as_deref()))
        .rule(RequiredUuid::new("to_warehouse_id", |e: &StockTransfer| &e.to_warehouse_id))
        .rule(OptionalNotBlank::new("to_location", |e: &StockTransfer| e.to_location.as_deref()))
        .rule(NonNegative::new("total_items", |e: &StockTransfer| e.total_items))
        .rule(NonNegative::new("total_quantity", |e: &StockTransfer| e.total_quantity))
        .rule(NonNegative::new("total_value", |e: &StockTransfer| e.total_value))
        .rule(RequiredString::new("currency", |e: &StockTransfer| &e.currency))
        .rule(OptionalNotBlank::new("shipping_method", |e: &StockTransfer| e.shipping_method.as_deref()))
        .rule(OptionalNotBlank::new("carrier", |e: &StockTransfer| e.carrier.as_deref()))
        .rule(OptionalNotBlank::new("tracking_number", |e: &StockTransfer| e.tracking_number.as_deref()))
        .rule(NonNegative::new("shipping_cost", |e: &StockTransfer| e.shipping_cost))
        .rule(OptionalNotBlank::new("reason", |e: &StockTransfer| e.reason.as_deref()))
        .rule(OptionalNotBlank::new("notes", |e: &StockTransfer| e.notes.as_deref()))
        .rule(OptionalNotBlank::new("receiving_notes", |e: &StockTransfer| e.receiving_notes.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
