//! Validator for Stock entity
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Stock>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString, RequiredUuid};
use crate::domain::entity::Stock;

/// Validator type alias for Stock entities.
pub type StockValidator = EntityValidator<Stock>;

/// Build a validator for Stock with all schema-defined field rules.
pub fn stock_validator() -> StockValidator {
    EntityValidator::new()
        .rule(RequiredUuid::new("provider_id", |e: &Stock| &e.provider_id))
        .rule(RequiredUuid::new("product_id", |e: &Stock| &e.product_id))
        .rule(RequiredUuid::new("warehouse_id", |e: &Stock| &e.warehouse_id))
        .rule(NonNegative::new("quantity_reserved", |e: &Stock| e.quantity_reserved))
        .rule(NonNegative::new("quantity_on_order", |e: &Stock| e.quantity_on_order))
        .rule(NonNegative::new("quantity_in_transit", |e: &Stock| e.quantity_in_transit))
        .rule(NonNegative::new("quantity_quarantine", |e: &Stock| e.quantity_quarantine))
        .rule(NonNegative::new("quantity_damaged", |e: &Stock| e.quantity_damaged))
        .rule(RequiredString::new("currency", |e: &Stock| &e.currency))
        .rule(NonNegative::new("unit_cost", |e: &Stock| e.unit_cost))
        .rule(NonNegative::new("total_value", |e: &Stock| e.total_value))
        .rule(OptionalNotBlank::new("bin_location", |e: &Stock| e.bin_location.as_deref()))
        .rule(OptionalNotBlank::new("notes", |e: &Stock| e.notes.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
