//! Validator for StorageCategoryCapacity entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<StorageCategoryCapacity>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::StorageCategoryCapacity;

/// Validator type alias for StorageCategoryCapacity entities.
pub type StorageCategoryCapacityValidator = EntityValidator<StorageCategoryCapacity>;

/// Build a validator for StorageCategoryCapacity with all schema-defined field rules.
pub fn storage_category_capacity_validator() -> StorageCategoryCapacityValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
