//! Auth configuration for Bin handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Bin>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::BinService;
use crate::domain::entity::Bin;

/// Permission string constants for Bin operations.
pub mod permissions {
    pub const LIST:        &str = "bin:list";
    pub const READ:        &str = "bin:read";
    pub const CREATE:      &str = "bin:create";
    pub const UPDATE:      &str = "bin:update";
    pub const DELETE:      &str = "bin:delete";
    pub const RESTORE:     &str = "bin:restore";
    pub const TRASH:       &str = "bin:trash";
    pub const EMPTY_TRASH: &str = "bin:empty_trash";
    pub const BULK_CREATE: &str = "bin:bulk_create";
    pub const UPSERT:      &str = "bin:upsert";
}

/// Resource policy for Bin — maps CRUD actions to permission strings.
pub struct BinPolicy;

#[async_trait]
impl ResourcePolicy<Bin> for BinPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Bin,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Bin handlers.
///
/// Wraps `BinService` and checks `BinPolicy` before delegating.
pub type BinGuard = PermissionGuard<Bin>;

/// Service-integrated permission guard for Bin (for use in generated handlers).
pub type BinServiceGuard = ServicePermissionGuard<Bin, BinService, BinPolicy>;

// <<< CUSTOM
// END CUSTOM
