//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod delivery_note_auth;
pub mod delivery_note_item_auth;
pub mod purchase_receipt_auth;
pub mod purchase_receipt_item_auth;
pub mod stock_entry_auth;
pub mod stock_entry_item_auth;
pub mod stock_ledger_entry_auth;
pub mod bin_auth;
pub mod stock_reconciliation_auth;
pub mod stock_reconciliation_item_auth;
pub mod warehouse_auth;
pub mod stock_item_auth;

pub use delivery_note_auth::{DeliveryNotePolicy, DeliveryNoteGuard, DeliveryNoteServiceGuard};
pub use delivery_note_item_auth::{DeliveryNoteItemPolicy, DeliveryNoteItemGuard, DeliveryNoteItemServiceGuard};
pub use purchase_receipt_auth::{PurchaseReceiptPolicy, PurchaseReceiptGuard, PurchaseReceiptServiceGuard};
pub use purchase_receipt_item_auth::{PurchaseReceiptItemPolicy, PurchaseReceiptItemGuard, PurchaseReceiptItemServiceGuard};
pub use stock_entry_auth::{StockEntryPolicy, StockEntryGuard, StockEntryServiceGuard};
pub use stock_entry_item_auth::{StockEntryItemPolicy, StockEntryItemGuard, StockEntryItemServiceGuard};
pub use stock_ledger_entry_auth::{StockLedgerEntryPolicy, StockLedgerEntryGuard, StockLedgerEntryServiceGuard};
pub use bin_auth::{BinPolicy, BinGuard, BinServiceGuard};
pub use stock_reconciliation_auth::{StockReconciliationPolicy, StockReconciliationGuard, StockReconciliationServiceGuard};
pub use stock_reconciliation_item_auth::{StockReconciliationItemPolicy, StockReconciliationItemGuard, StockReconciliationItemServiceGuard};
pub use warehouse_auth::{WarehousePolicy, WarehouseGuard, WarehouseServiceGuard};
pub use stock_item_auth::{StockItemPolicy, StockItemGuard, StockItemServiceGuard};

// <<< CUSTOM
// END CUSTOM
