//! Auth configuration for PurchaseReceiptItem handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<PurchaseReceiptItem>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::PurchaseReceiptItemService;
use crate::domain::entity::PurchaseReceiptItem;

/// Permission string constants for PurchaseReceiptItem operations.
pub mod permissions {
    pub const LIST:        &str = "purchase_receipt_item:list";
    pub const READ:        &str = "purchase_receipt_item:read";
    pub const CREATE:      &str = "purchase_receipt_item:create";
    pub const UPDATE:      &str = "purchase_receipt_item:update";
    pub const DELETE:      &str = "purchase_receipt_item:delete";
    pub const RESTORE:     &str = "purchase_receipt_item:restore";
    pub const TRASH:       &str = "purchase_receipt_item:trash";
    pub const EMPTY_TRASH: &str = "purchase_receipt_item:empty_trash";
    pub const BULK_CREATE: &str = "purchase_receipt_item:bulk_create";
    pub const UPSERT:      &str = "purchase_receipt_item:upsert";
}

/// Resource policy for PurchaseReceiptItem — maps CRUD actions to permission strings.
pub struct PurchaseReceiptItemPolicy;

#[async_trait]
impl ResourcePolicy<PurchaseReceiptItem> for PurchaseReceiptItemPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &PurchaseReceiptItem,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for PurchaseReceiptItem handlers.
///
/// Wraps `PurchaseReceiptItemService` and checks `PurchaseReceiptItemPolicy` before delegating.
pub type PurchaseReceiptItemGuard = PermissionGuard<PurchaseReceiptItem>;

/// Service-integrated permission guard for PurchaseReceiptItem (for use in generated handlers).
pub type PurchaseReceiptItemServiceGuard = ServicePermissionGuard<PurchaseReceiptItem, PurchaseReceiptItemService, PurchaseReceiptItemPolicy>;

// <<< CUSTOM
// END CUSTOM
