//! Auth configuration for StockEntry handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<StockEntry>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::StockEntryService;
use crate::domain::entity::StockEntry;

/// Permission string constants for StockEntry operations.
pub mod permissions {
    pub const LIST:        &str = "stock_entry:list";
    pub const READ:        &str = "stock_entry:read";
    pub const CREATE:      &str = "stock_entry:create";
    pub const UPDATE:      &str = "stock_entry:update";
    pub const DELETE:      &str = "stock_entry:delete";
    pub const RESTORE:     &str = "stock_entry:restore";
    pub const TRASH:       &str = "stock_entry:trash";
    pub const EMPTY_TRASH: &str = "stock_entry:empty_trash";
    pub const BULK_CREATE: &str = "stock_entry:bulk_create";
    pub const UPSERT:      &str = "stock_entry:upsert";
}

/// Resource policy for StockEntry — maps CRUD actions to permission strings.
pub struct StockEntryPolicy;

#[async_trait]
impl ResourcePolicy<StockEntry> for StockEntryPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &StockEntry,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for StockEntry handlers.
///
/// Wraps `StockEntryService` and checks `StockEntryPolicy` before delegating.
pub type StockEntryGuard = PermissionGuard<StockEntry>;

/// Service-integrated permission guard for StockEntry (for use in generated handlers).
pub type StockEntryServiceGuard = ServicePermissionGuard<StockEntry, StockEntryService, StockEntryPolicy>;

// <<< CUSTOM
// END CUSTOM
