//! Auth configuration for StockAdjustment handlers
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<StockAdjustment>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::StockAdjustmentService;
use crate::domain::entity::StockAdjustment;

/// Permission string constants for StockAdjustment operations.
pub mod permissions {
    pub const LIST:        &str = "stock_adjustment:list";
    pub const READ:        &str = "stock_adjustment:read";
    pub const CREATE:      &str = "stock_adjustment:create";
    pub const UPDATE:      &str = "stock_adjustment:update";
    pub const DELETE:      &str = "stock_adjustment:delete";
    pub const RESTORE:     &str = "stock_adjustment:restore";
    pub const TRASH:       &str = "stock_adjustment:trash";
    pub const EMPTY_TRASH: &str = "stock_adjustment:empty_trash";
    pub const BULK_CREATE: &str = "stock_adjustment:bulk_create";
    pub const UPSERT:      &str = "stock_adjustment:upsert";
}

/// Resource policy for StockAdjustment — maps CRUD actions to permission strings.
pub struct StockAdjustmentPolicy;

#[async_trait]
impl ResourcePolicy<StockAdjustment> for StockAdjustmentPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &StockAdjustment,
        ctx: &backbone_auth::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read   => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update => permissions::UPDATE,
            ResourceAction::Delete => permissions::DELETE,
        };
        ctx.has_permission(required)
    }
}

/// Permission guard for StockAdjustment handlers.
///
/// Wraps `StockAdjustmentService` and checks `StockAdjustmentPolicy` before delegating.
pub type StockAdjustmentGuard = PermissionGuard<StockAdjustment, StockAdjustmentService, StockAdjustmentPolicy>;

/// Service-integrated permission guard for StockAdjustment (for use in generated handlers).
pub type StockAdjustmentServiceGuard = ServicePermissionGuard<StockAdjustment, StockAdjustmentService, StockAdjustmentPolicy>;

// <<< CUSTOM
// END CUSTOM
