//! Auth configuration for StockReconciliationItem handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<StockReconciliationItem>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::StockReconciliationItemService;
use crate::domain::entity::StockReconciliationItem;

/// Permission string constants for StockReconciliationItem operations.
pub mod permissions {
    pub const LIST:        &str = "stock_reconciliation_item:list";
    pub const READ:        &str = "stock_reconciliation_item:read";
    pub const CREATE:      &str = "stock_reconciliation_item:create";
    pub const UPDATE:      &str = "stock_reconciliation_item:update";
    pub const DELETE:      &str = "stock_reconciliation_item:delete";
    pub const RESTORE:     &str = "stock_reconciliation_item:restore";
    pub const TRASH:       &str = "stock_reconciliation_item:trash";
    pub const EMPTY_TRASH: &str = "stock_reconciliation_item:empty_trash";
    pub const BULK_CREATE: &str = "stock_reconciliation_item:bulk_create";
    pub const UPSERT:      &str = "stock_reconciliation_item:upsert";
}

/// Resource policy for StockReconciliationItem — maps CRUD actions to permission strings.
pub struct StockReconciliationItemPolicy;

#[async_trait]
impl ResourcePolicy<StockReconciliationItem> for StockReconciliationItemPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &StockReconciliationItem,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for StockReconciliationItem handlers.
///
/// Wraps `StockReconciliationItemService` and checks `StockReconciliationItemPolicy` before delegating.
pub type StockReconciliationItemGuard = PermissionGuard<StockReconciliationItem>;

/// Service-integrated permission guard for StockReconciliationItem (for use in generated handlers).
pub type StockReconciliationItemServiceGuard = ServicePermissionGuard<StockReconciliationItem, StockReconciliationItemService, StockReconciliationItemPolicy>;

// <<< CUSTOM
// END CUSTOM
