//! Bin API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Bin CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// BIN TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Bin
pub struct BinTestData;

impl TestDataGenerator for BinTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "item_id": Uuid::new_v4().to_string(),
            "warehouse_id": Uuid::new_v4().to_string(),
            "actual_qty": 0,
            "reserved_qty": 0,
            "valuation_rate": 0,
            "stock_value": 0,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "item_id": Uuid::new_v4().to_string(),
            "warehouse_id": Uuid::new_v4().to_string(),
            "actual_qty": 0,
            "reserved_qty": 0,
            "valuation_rate": 0,
            "stock_value": 0,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/warehouses", &super::warehouse_api_test::WarehouseTestData).await {
            deps.push(("warehouse_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// BIN API TEST
// ============================================================================

/// Bin API test suite
pub struct BinApiTest {
    inner: GenericCrudTest<BinTestData>,
}

impl BinApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/bins", "Bin");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, BinTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for BinApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_bin_crud() {
        let mut test = BinApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Bin specific tests here
// <<< CUSTOM TESTS END >>>
