//! PurchaseOrder API Integration Tests
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Tests the PurchaseOrder CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// PURCHASEORDER TEST DATA GENERATOR
// ============================================================================

/// Test data generator for PurchaseOrder
pub struct PurchaseOrderTestData;

impl TestDataGenerator for PurchaseOrderTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "provider_id": null,
            "po_number": null,
            "reference_number": null,
            "po_type": null,
            "supplier_id": null,
            "supplier_name": null,
            "supplier_contact_person": null,
            "warehouse_id": null,
            "delivery_address": null,
            "order_date": null,
            "expected_date": null,
            "delivery_date": null,
            "expiry_date": null,
            "currency": null,
            "subtotal": null,
            "discount_percent": null,
            "discount_amount": null,
            "tax_percent": null,
            "tax_amount": null,
            "shipping_cost": null,
            "other_cost": null,
            "total_amount": null,
            "payment_terms": null,
            "payment_due_date": null,
            "status": null,
            "requires_approval": null,
            "submitted_at": now,
            "submitted_by": null,
            "approved_at": now,
            "approved_by": null,
            "rejected_at": now,
            "rejected_by": null,
            "rejection_reason": null,
            "cancelled_at": now,
            "cancelled_by": null,
            "cancellation_reason": null,
            "completed_at": now,
            "attachments": null,
            "supplier_notes": null,
            "internal_notes": null,
            "data": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "provider_id": null,
            "po_number": null,
            "reference_number": null,
            "po_type": null,
            "supplier_id": null,
            "supplier_name": null,
            "supplier_contact_person": null,
            "warehouse_id": null,
            "delivery_address": null,
            "order_date": null,
            "expected_date": null,
            "delivery_date": null,
            "expiry_date": null,
            "currency": null,
            "subtotal": null,
            "discount_percent": null,
            "discount_amount": null,
            "tax_percent": null,
            "tax_amount": null,
            "shipping_cost": null,
            "other_cost": null,
            "total_amount": null,
            "payment_terms": null,
            "payment_due_date": null,
            "status": null,
            "requires_approval": null,
            "submitted_at": now,
            "submitted_by": null,
            "approved_at": now,
            "approved_by": null,
            "rejected_at": now,
            "rejected_by": null,
            "rejection_reason": null,
            "cancelled_at": now,
            "cancelled_by": null,
            "cancellation_reason": null,
            "completed_at": now,
            "attachments": null,
            "supplier_notes": null,
            "internal_notes": null,
            "data": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// PURCHASEORDER API TEST
// ============================================================================

/// PurchaseOrder API test suite
pub struct PurchaseOrderApiTest {
    inner: GenericCrudTest<PurchaseOrderTestData>,
}

impl PurchaseOrderApiTest {
    pub fn new() -> Self {
        let config = CrudTestConfig::new("/api/v1/purchase_orders", "PurchaseOrder");
        Self {
            inner: GenericCrudTest::new(config, PurchaseOrderTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for PurchaseOrderApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_purchase_order_crud() {
        let mut test = PurchaseOrderApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add PurchaseOrder specific tests here
// <<< CUSTOM TESTS END >>>
