//! GoodsMovement flow implementation
//!
//! Generated by metaphor-schema
//!
//! On submitting a Purchase Receipt / Delivery Note / Stock Reconciliation: append an immutable SLE
//! per line, update the per-(item,warehouse) Bin balance by the moving-average rule, then emit a
//! balanced AccountingPost and reconcile the voucher's posting_state.

use serde::{Deserialize, Serialize};
use std::sync::Arc;
use chrono;
use backbone_core::flow::{WorkflowStep, WorkflowContext};

/// Error type for flow execution
#[derive(Debug, Clone, thiserror::Error)]
pub enum FlowError {
    #[error("No current step to execute")]
    NoCurrentStep,

    #[error("Step execution failed: {0}")]
    StepFailed(String),

    #[error("Condition evaluation failed: {0}")]
    ConditionFailed(String),

    #[error("Compensation failed: {0}")]
    CompensationFailed(String),

    #[error("Flow timed out")]
    Timeout,

    #[error("Flow cancelled")]
    Cancelled,

    #[error("Invalid state transition: {from} -> {to}")]
    InvalidTransition { from: String, to: String },
}

/// Execution status for GoodsMovement flow
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GoodsMovementFlowStatus {
    /// Flow is pending execution
    Pending,
    /// Flow is currently running
    Running,
    /// Flow is waiting for an event or condition
    Waiting,
    /// Flow completed successfully
    Completed,
    /// Flow failed
    Failed,
    /// Flow was cancelled
    Cancelled,
    /// Flow is compensating (rolling back)
    Compensating,
}

/// Steps in GoodsMovement flow
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GoodsMovementFlowStep {
    /// validate
    Validate,
    /// write_ledger
    WriteLedger,
    /// emit_post
    EmitPost,
    /// done
    Done,
    /// post_failed
    PostFailed,
    /// rejected
    Rejected,
}

/// Instance of GoodsMovement flow execution
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GoodsMovementFlowInstance {
    /// Unique instance ID
    pub id: String,
    /// Current status
    pub status: GoodsMovementFlowStatus,
    /// Current step
    pub current_step: Option<GoodsMovementFlowStep>,
    /// Flow context (variables)
    pub context: serde_json::Value,
    /// Completed steps
    pub completed_steps: Vec<GoodsMovementFlowStep>,
    /// Error if failed
    pub error: Option<String>,
    /// Created timestamp
    pub created_at: chrono::DateTime<chrono::Utc>,
    /// Updated timestamp
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

impl GoodsMovementFlowInstance {
    /// Create a new flow instance
    pub fn new(id: impl Into<String>) -> Self {
        let now = chrono::Utc::now();
        Self {
            id: id.into(),
            status: GoodsMovementFlowStatus::Pending,
            current_step: None,
            context: serde_json::json!({}),
            completed_steps: Vec::new(),
            error: None,
            created_at: now,
            updated_at: now,
        }
    }

    /// Check if flow is complete
    pub fn is_complete(&self) -> bool {
        matches!(
            self.status,
            GoodsMovementFlowStatus::Completed | GoodsMovementFlowStatus::Failed | GoodsMovementFlowStatus::Cancelled
        )
    }

    /// Check if flow is running
    pub fn is_running(&self) -> bool {
        matches!(
            self.status,
            GoodsMovementFlowStatus::Running | GoodsMovementFlowStatus::Waiting
        )
    }

    /// Set a context variable
    pub fn set_context(&mut self, key: &str, value: serde_json::Value) {
        if let serde_json::Value::Object(ref mut map) = self.context {
            map.insert(key.to_string(), value);
        }
        self.updated_at = chrono::Utc::now();
    }

    /// Get a context variable
    pub fn get_context(&self, key: &str) -> Option<&serde_json::Value> {
        if let serde_json::Value::Object(ref map) = self.context {
            map.get(key)
        } else {
            None
        }
    }
}

// Phase 1: FlowInstance satisfies backbone_core::flow::WorkflowContext.
// The entity() accessor requires the entity to be carried in the instance;
// add `pub entity: GoodsMovement` in the // <<< CUSTOM section and remove the todo!.
#[allow(unused_variables)]
impl WorkflowContext<GoodsMovementFlowInstance> for GoodsMovementFlowInstance {
    fn entity(&self) -> &GoodsMovementFlowInstance { self }
    fn set_var(&mut self, key: &str, value: serde_json::Value) {
        self.set_context(key, value);
    }
    fn get_var(&self, key: &str) -> Option<&serde_json::Value> {
        self.get_context(key)
    }
}

/// Step handler trait for GoodsMovement flow
#[async_trait::async_trait]
pub trait GoodsMovementStepHandler: Send + Sync {
    /// Handle validate step
    async fn handle_validate(
        &self,
        instance: &mut GoodsMovementFlowInstance,
    ) -> Result<Option<GoodsMovementFlowStep>, FlowError>;

    /// Handle write_ledger step
    async fn handle_write_ledger(
        &self,
        instance: &mut GoodsMovementFlowInstance,
    ) -> Result<Option<GoodsMovementFlowStep>, FlowError>;

    /// Handle emit_post step
    async fn handle_emit_post(
        &self,
        instance: &mut GoodsMovementFlowInstance,
    ) -> Result<Option<GoodsMovementFlowStep>, FlowError>;

    /// Handle terminal step done
    async fn handle_done(
        &self,
        instance: &mut GoodsMovementFlowInstance,
    ) -> Result<(), FlowError>;

    /// Handle terminal step post_failed
    async fn handle_post_failed(
        &self,
        instance: &mut GoodsMovementFlowInstance,
    ) -> Result<(), FlowError>;

    /// Handle terminal step rejected
    async fn handle_rejected(
        &self,
        instance: &mut GoodsMovementFlowInstance,
    ) -> Result<(), FlowError>;

}

/// Executor for GoodsMovement flow
pub struct GoodsMovementFlowExecutor<H: GoodsMovementStepHandler> {
    handler: Arc<H>,
}

impl<H: GoodsMovementStepHandler> GoodsMovementFlowExecutor<H> {
    /// Create a new flow executor
    pub fn new(handler: Arc<H>) -> Self {
        Self { handler }
    }

    /// Start a new flow instance
    pub async fn start(&self, instance_id: impl Into<String>) -> Result<GoodsMovementFlowInstance, FlowError> {
        let mut instance = GoodsMovementFlowInstance::new(instance_id);
        instance.status = GoodsMovementFlowStatus::Running;
        instance.current_step = Some(GoodsMovementFlowStep::Validate);
        Ok(instance)
    }

    /// Execute the current step
    pub async fn execute_step(&self, instance: &mut GoodsMovementFlowInstance) -> Result<(), FlowError> {
        let current_step = match instance.current_step {
            Some(step) => step,
            None => return Err(FlowError::NoCurrentStep),
        };

        let next_step = match current_step {
            GoodsMovementFlowStep::Validate => {
                self.handler.handle_validate(instance).await?
            }
            GoodsMovementFlowStep::WriteLedger => {
                self.handler.handle_write_ledger(instance).await?
            }
            GoodsMovementFlowStep::EmitPost => {
                self.handler.handle_emit_post(instance).await?
            }
            GoodsMovementFlowStep::Done => {
                self.handler.handle_done(instance).await?;
                None // Terminal step
            }
            GoodsMovementFlowStep::PostFailed => {
                self.handler.handle_post_failed(instance).await?;
                None // Terminal step
            }
            GoodsMovementFlowStep::Rejected => {
                self.handler.handle_rejected(instance).await?;
                None // Terminal step
            }
        };

        // Mark current step as completed
        instance.completed_steps.push(current_step);

        // Move to next step
        match next_step {
            Some(next) => {
                instance.current_step = Some(next);
            }
            None => {
                instance.current_step = None;
                instance.status = GoodsMovementFlowStatus::Completed;
            }
        }

        instance.updated_at = chrono::Utc::now();
        Ok(())
    }

    /// Run the flow to completion
    pub async fn run(&self, instance: &mut GoodsMovementFlowInstance) -> Result<(), FlowError> {
        while !instance.is_complete() && instance.status != GoodsMovementFlowStatus::Waiting {
            self.execute_step(instance).await?;
        }
        Ok(())
    }

    /// Cancel the flow
    pub fn cancel(&self, instance: &mut GoodsMovementFlowInstance) {
        instance.status = GoodsMovementFlowStatus::Cancelled;
        instance.updated_at = chrono::Utc::now();
    }

    /// Mark flow as failed
    pub fn fail(&self, instance: &mut GoodsMovementFlowInstance, error: impl Into<String>) {
        instance.status = GoodsMovementFlowStatus::Failed;
        instance.error = Some(error.into());
        instance.updated_at = chrono::Utc::now();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_flow_instance_creation() {
        let instance = GoodsMovementFlowInstance::new("test-1");
        assert_eq!(instance.id, "test-1");
        assert_eq!(instance.status, GoodsMovementFlowStatus::Pending);
        assert!(!instance.is_complete());
    }

    #[test]
    fn test_flow_context() {
        let mut instance = GoodsMovementFlowInstance::new("test-2");
        instance.set_context("key", serde_json::json!("value"));
        let value = instance.get_context("key");
        assert_eq!(value, Some(&serde_json::json!("value")));
    }

    #[test]
    fn test_flow_status_transitions() {
        let mut instance = GoodsMovementFlowInstance::new("test-3");
        assert!(!instance.is_running());

        instance.status = GoodsMovementFlowStatus::Running;
        assert!(instance.is_running());
        assert!(!instance.is_complete());

        instance.status = GoodsMovementFlowStatus::Completed;
        assert!(instance.is_complete());
        assert!(!instance.is_running());
    }
}
