//! Public services for Inventory module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Inventory module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait InventoryQueryService: Send + Sync {
    /// Get DeliveryNote by ID
    async fn get_delivery_note(&self, id: DeliveryNoteId) -> Result<Option<DeliveryNoteDto>>;

    /// Get DeliveryNote summary by ID
    async fn get_delivery_note_summary(&self, id: DeliveryNoteId) -> Result<Option<DeliveryNoteSummary>>;

    /// Check if DeliveryNote exists
    async fn delivery_note_exists(&self, id: DeliveryNoteId) -> Result<bool>;

    /// Get DeliveryNoteItem by ID
    async fn get_delivery_note_item(&self, id: DeliveryNoteItemId) -> Result<Option<DeliveryNoteItemDto>>;

    /// Get DeliveryNoteItem summary by ID
    async fn get_delivery_note_item_summary(&self, id: DeliveryNoteItemId) -> Result<Option<DeliveryNoteItemSummary>>;

    /// Check if DeliveryNoteItem exists
    async fn delivery_note_item_exists(&self, id: DeliveryNoteItemId) -> Result<bool>;

    /// Get PurchaseReceipt by ID
    async fn get_purchase_receipt(&self, id: PurchaseReceiptId) -> Result<Option<PurchaseReceiptDto>>;

    /// Get PurchaseReceipt summary by ID
    async fn get_purchase_receipt_summary(&self, id: PurchaseReceiptId) -> Result<Option<PurchaseReceiptSummary>>;

    /// Check if PurchaseReceipt exists
    async fn purchase_receipt_exists(&self, id: PurchaseReceiptId) -> Result<bool>;

    /// Get PurchaseReceiptItem by ID
    async fn get_purchase_receipt_item(&self, id: PurchaseReceiptItemId) -> Result<Option<PurchaseReceiptItemDto>>;

    /// Get PurchaseReceiptItem summary by ID
    async fn get_purchase_receipt_item_summary(&self, id: PurchaseReceiptItemId) -> Result<Option<PurchaseReceiptItemSummary>>;

    /// Check if PurchaseReceiptItem exists
    async fn purchase_receipt_item_exists(&self, id: PurchaseReceiptItemId) -> Result<bool>;

    /// Get StockEntry by ID
    async fn get_stock_entry(&self, id: StockEntryId) -> Result<Option<StockEntryDto>>;

    /// Get StockEntry summary by ID
    async fn get_stock_entry_summary(&self, id: StockEntryId) -> Result<Option<StockEntrySummary>>;

    /// Check if StockEntry exists
    async fn stock_entry_exists(&self, id: StockEntryId) -> Result<bool>;

    /// Get StockEntryItem by ID
    async fn get_stock_entry_item(&self, id: StockEntryItemId) -> Result<Option<StockEntryItemDto>>;

    /// Get StockEntryItem summary by ID
    async fn get_stock_entry_item_summary(&self, id: StockEntryItemId) -> Result<Option<StockEntryItemSummary>>;

    /// Check if StockEntryItem exists
    async fn stock_entry_item_exists(&self, id: StockEntryItemId) -> Result<bool>;

    /// Get StockLedgerEntry by ID
    async fn get_stock_ledger_entry(&self, id: StockLedgerEntryId) -> Result<Option<StockLedgerEntryDto>>;

    /// Get StockLedgerEntry summary by ID
    async fn get_stock_ledger_entry_summary(&self, id: StockLedgerEntryId) -> Result<Option<StockLedgerEntrySummary>>;

    /// Check if StockLedgerEntry exists
    async fn stock_ledger_entry_exists(&self, id: StockLedgerEntryId) -> Result<bool>;

    /// Get Bin by ID
    async fn get_bin(&self, id: BinId) -> Result<Option<BinDto>>;

    /// Get Bin summary by ID
    async fn get_bin_summary(&self, id: BinId) -> Result<Option<BinSummary>>;

    /// Check if Bin exists
    async fn bin_exists(&self, id: BinId) -> Result<bool>;

    /// Get StockReconciliation by ID
    async fn get_stock_reconciliation(&self, id: StockReconciliationId) -> Result<Option<StockReconciliationDto>>;

    /// Get StockReconciliation summary by ID
    async fn get_stock_reconciliation_summary(&self, id: StockReconciliationId) -> Result<Option<StockReconciliationSummary>>;

    /// Check if StockReconciliation exists
    async fn stock_reconciliation_exists(&self, id: StockReconciliationId) -> Result<bool>;

    /// Get StockReconciliationItem by ID
    async fn get_stock_reconciliation_item(&self, id: StockReconciliationItemId) -> Result<Option<StockReconciliationItemDto>>;

    /// Get StockReconciliationItem summary by ID
    async fn get_stock_reconciliation_item_summary(&self, id: StockReconciliationItemId) -> Result<Option<StockReconciliationItemSummary>>;

    /// Check if StockReconciliationItem exists
    async fn stock_reconciliation_item_exists(&self, id: StockReconciliationItemId) -> Result<bool>;

    /// Get Warehouse by ID
    async fn get_warehouse(&self, id: WarehouseId) -> Result<Option<WarehouseDto>>;

    /// Get Warehouse summary by ID
    async fn get_warehouse_summary(&self, id: WarehouseId) -> Result<Option<WarehouseSummary>>;

    /// Check if Warehouse exists
    async fn warehouse_exists(&self, id: WarehouseId) -> Result<bool>;

    /// Get StockItem by ID
    async fn get_stock_item(&self, id: StockItemId) -> Result<Option<StockItemDto>>;

    /// Get StockItem summary by ID
    async fn get_stock_item_summary(&self, id: StockItemId) -> Result<Option<StockItemSummary>>;

    /// Check if StockItem exists
    async fn stock_item_exists(&self, id: StockItemId) -> Result<bool>;

}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
