//! Inventory Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::PickingBatchService;
pub use application::service::DeliveryNoteService;
pub use application::service::DeliveryNoteItemService;
pub use application::service::InventoryCompanySettingService;
pub use application::service::LandedCostService;
pub use application::service::LandedCostLineService;
pub use application::service::LandedCostAdjustmentLineService;
pub use application::service::LocationService;
pub use application::service::StockMoveService;
pub use application::service::StockMoveLineService;
pub use application::service::OperationTypeService;
pub use application::service::TransferService;
pub use application::service::RouteService;
pub use application::service::RouteRuleService;
pub use application::service::ReorderingRuleService;
pub use application::service::PurchaseReceiptService;
pub use application::service::PurchaseReceiptItemService;
pub use application::service::QuantService;
pub use application::service::ScrapService;
pub use application::service::ScrapReasonTagService;
pub use application::service::StockEntryService;
pub use application::service::StockEntryItemService;
pub use application::service::StockLedgerEntryService;
pub use application::service::BinService;
pub use application::service::StockReconciliationService;
pub use application::service::StockReconciliationItemService;
pub use application::service::PackageTypeService;
pub use application::service::StorageCategoryService;
pub use application::service::StorageCategoryCapacityService;
pub use application::service::PutawayRuleService;
pub use application::service::LotService;
pub use application::service::PackageService;
pub use application::service::WarehouseService;
pub use application::service::StockItemService;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Inventory module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let inventory = InventoryModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = inventory.all_crud_routes();
/// ```
pub struct InventoryModule {
    pub(crate) picking_batch_service: Arc<PickingBatchService>,
    pub(crate) delivery_note_service: Arc<DeliveryNoteService>,
    pub(crate) delivery_note_item_service: Arc<DeliveryNoteItemService>,
    pub(crate) inventory_company_setting_service: Arc<InventoryCompanySettingService>,
    pub(crate) landed_cost_service: Arc<LandedCostService>,
    pub(crate) landed_cost_line_service: Arc<LandedCostLineService>,
    pub(crate) landed_cost_adjustment_line_service: Arc<LandedCostAdjustmentLineService>,
    pub(crate) location_service: Arc<LocationService>,
    pub(crate) stock_move_service: Arc<StockMoveService>,
    pub(crate) stock_move_line_service: Arc<StockMoveLineService>,
    pub(crate) operation_type_service: Arc<OperationTypeService>,
    pub(crate) transfer_service: Arc<TransferService>,
    pub(crate) route_service: Arc<RouteService>,
    pub(crate) route_rule_service: Arc<RouteRuleService>,
    pub(crate) reordering_rule_service: Arc<ReorderingRuleService>,
    pub(crate) purchase_receipt_service: Arc<PurchaseReceiptService>,
    pub(crate) purchase_receipt_item_service: Arc<PurchaseReceiptItemService>,
    pub(crate) quant_service: Arc<QuantService>,
    pub(crate) scrap_service: Arc<ScrapService>,
    pub(crate) scrap_reason_tag_service: Arc<ScrapReasonTagService>,
    pub(crate) stock_entry_service: Arc<StockEntryService>,
    pub(crate) stock_entry_item_service: Arc<StockEntryItemService>,
    pub(crate) stock_ledger_entry_service: Arc<StockLedgerEntryService>,
    pub(crate) bin_service: Arc<BinService>,
    pub(crate) stock_reconciliation_service: Arc<StockReconciliationService>,
    pub(crate) stock_reconciliation_item_service: Arc<StockReconciliationItemService>,
    pub(crate) package_type_service: Arc<PackageTypeService>,
    pub(crate) storage_category_service: Arc<StorageCategoryService>,
    pub(crate) storage_category_capacity_service: Arc<StorageCategoryCapacityService>,
    pub(crate) putaway_rule_service: Arc<PutawayRuleService>,
    pub(crate) lot_service: Arc<LotService>,
    pub(crate) package_service: Arc<PackageService>,
    pub(crate) warehouse_service: Arc<WarehouseService>,
    pub(crate) stock_item_service: Arc<StockItemService>,
    // <<< CUSTOM FIELDS
    // END CUSTOM
}

impl InventoryModule {
    /// Create a new module builder
    pub fn builder() -> InventoryModuleBuilder {
        InventoryModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_picking_batch_read_routes,
            create_delivery_note_routes,
            create_delivery_note_item_routes,
            create_inventory_company_setting_routes,
            create_landed_cost_routes,
            create_landed_cost_line_routes,
            create_landed_cost_adjustment_line_routes,
            create_location_routes,
            create_stock_move_routes,
            create_stock_move_line_routes,
            create_operation_type_routes,
            create_transfer_read_routes,
            create_route_routes,
            create_route_rule_routes,
            create_reordering_rule_routes,
            create_purchase_receipt_routes,
            create_purchase_receipt_item_routes,
            create_quant_routes,
            create_scrap_read_routes,
            create_scrap_reason_tag_routes,
            create_stock_entry_routes,
            create_stock_entry_item_routes,
            create_stock_ledger_entry_routes,
            create_bin_routes,
            create_stock_reconciliation_routes,
            create_stock_reconciliation_item_routes,
            create_package_type_routes,
            create_storage_category_routes,
            create_storage_category_capacity_routes,
            create_putaway_rule_routes,
            create_lot_routes,
            create_package_routes,
            create_warehouse_routes,
            create_stock_item_routes,
        };

        Router::new()
            .merge(create_picking_batch_read_routes(self.picking_batch_service.clone()))
            .merge(create_delivery_note_routes(self.delivery_note_service.clone()))
            .merge(create_delivery_note_item_routes(self.delivery_note_item_service.clone()))
            .merge(create_inventory_company_setting_routes(self.inventory_company_setting_service.clone()))
            .merge(create_landed_cost_routes(self.landed_cost_service.clone()))
            .merge(create_landed_cost_line_routes(self.landed_cost_line_service.clone()))
            .merge(create_landed_cost_adjustment_line_routes(self.landed_cost_adjustment_line_service.clone()))
            .merge(create_location_routes(self.location_service.clone()))
            .merge(create_stock_move_routes(self.stock_move_service.clone()))
            .merge(create_stock_move_line_routes(self.stock_move_line_service.clone()))
            .merge(create_operation_type_routes(self.operation_type_service.clone()))
            .merge(create_transfer_read_routes(self.transfer_service.clone()))
            .merge(create_route_routes(self.route_service.clone()))
            .merge(create_route_rule_routes(self.route_rule_service.clone()))
            .merge(create_reordering_rule_routes(self.reordering_rule_service.clone()))
            .merge(create_purchase_receipt_routes(self.purchase_receipt_service.clone()))
            .merge(create_purchase_receipt_item_routes(self.purchase_receipt_item_service.clone()))
            .merge(create_quant_routes(self.quant_service.clone()))
            .merge(create_scrap_read_routes(self.scrap_service.clone()))
            .merge(create_scrap_reason_tag_routes(self.scrap_reason_tag_service.clone()))
            .merge(create_stock_entry_routes(self.stock_entry_service.clone()))
            .merge(create_stock_entry_item_routes(self.stock_entry_item_service.clone()))
            .merge(create_stock_ledger_entry_routes(self.stock_ledger_entry_service.clone()))
            .merge(create_bin_routes(self.bin_service.clone()))
            .merge(create_stock_reconciliation_routes(self.stock_reconciliation_service.clone()))
            .merge(create_stock_reconciliation_item_routes(self.stock_reconciliation_item_service.clone()))
            .merge(create_package_type_routes(self.package_type_service.clone()))
            .merge(create_storage_category_routes(self.storage_category_service.clone()))
            .merge(create_storage_category_capacity_routes(self.storage_category_capacity_service.clone()))
            .merge(create_putaway_rule_routes(self.putaway_rule_service.clone()))
            .merge(create_lot_routes(self.lot_service.clone()))
            .merge(create_package_routes(self.package_service.clone()))
            .merge(create_warehouse_routes(self.warehouse_service.clone()))
            .merge(create_stock_item_routes(self.stock_item_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_picking_batch_read_routes,
            create_delivery_note_read_routes,
            create_delivery_note_item_read_routes,
            create_inventory_company_setting_read_routes,
            create_landed_cost_read_routes,
            create_landed_cost_line_read_routes,
            create_landed_cost_adjustment_line_read_routes,
            create_location_read_routes,
            create_stock_move_read_routes,
            create_stock_move_line_read_routes,
            create_operation_type_read_routes,
            create_transfer_read_routes,
            create_route_read_routes,
            create_route_rule_read_routes,
            create_reordering_rule_read_routes,
            create_purchase_receipt_read_routes,
            create_purchase_receipt_item_read_routes,
            create_quant_read_routes,
            create_scrap_read_routes,
            create_scrap_reason_tag_read_routes,
            create_stock_entry_read_routes,
            create_stock_entry_item_read_routes,
            create_stock_ledger_entry_read_routes,
            create_bin_read_routes,
            create_stock_reconciliation_read_routes,
            create_stock_reconciliation_item_read_routes,
            create_package_type_read_routes,
            create_storage_category_read_routes,
            create_storage_category_capacity_read_routes,
            create_putaway_rule_read_routes,
            create_lot_read_routes,
            create_package_read_routes,
            create_warehouse_read_routes,
            create_stock_item_read_routes,
        };

        Router::new()
            .merge(create_picking_batch_read_routes(self.picking_batch_service.clone()))
            .merge(create_delivery_note_read_routes(self.delivery_note_service.clone()))
            .merge(create_delivery_note_item_read_routes(self.delivery_note_item_service.clone()))
            .merge(create_inventory_company_setting_read_routes(self.inventory_company_setting_service.clone()))
            .merge(create_landed_cost_read_routes(self.landed_cost_service.clone()))
            .merge(create_landed_cost_line_read_routes(self.landed_cost_line_service.clone()))
            .merge(create_landed_cost_adjustment_line_read_routes(self.landed_cost_adjustment_line_service.clone()))
            .merge(create_location_read_routes(self.location_service.clone()))
            .merge(create_stock_move_read_routes(self.stock_move_service.clone()))
            .merge(create_stock_move_line_read_routes(self.stock_move_line_service.clone()))
            .merge(create_operation_type_read_routes(self.operation_type_service.clone()))
            .merge(create_transfer_read_routes(self.transfer_service.clone()))
            .merge(create_route_read_routes(self.route_service.clone()))
            .merge(create_route_rule_read_routes(self.route_rule_service.clone()))
            .merge(create_reordering_rule_read_routes(self.reordering_rule_service.clone()))
            .merge(create_purchase_receipt_read_routes(self.purchase_receipt_service.clone()))
            .merge(create_purchase_receipt_item_read_routes(self.purchase_receipt_item_service.clone()))
            .merge(create_quant_read_routes(self.quant_service.clone()))
            .merge(create_scrap_read_routes(self.scrap_service.clone()))
            .merge(create_scrap_reason_tag_read_routes(self.scrap_reason_tag_service.clone()))
            .merge(create_stock_entry_read_routes(self.stock_entry_service.clone()))
            .merge(create_stock_entry_item_read_routes(self.stock_entry_item_service.clone()))
            .merge(create_stock_ledger_entry_read_routes(self.stock_ledger_entry_service.clone()))
            .merge(create_bin_read_routes(self.bin_service.clone()))
            .merge(create_stock_reconciliation_read_routes(self.stock_reconciliation_service.clone()))
            .merge(create_stock_reconciliation_item_read_routes(self.stock_reconciliation_item_service.clone()))
            .merge(create_package_type_read_routes(self.package_type_service.clone()))
            .merge(create_storage_category_read_routes(self.storage_category_service.clone()))
            .merge(create_storage_category_capacity_read_routes(self.storage_category_capacity_service.clone()))
            .merge(create_putaway_rule_read_routes(self.putaway_rule_service.clone()))
            .merge(create_lot_read_routes(self.lot_service.clone()))
            .merge(create_package_read_routes(self.package_service.clone()))
            .merge(create_warehouse_read_routes(self.warehouse_service.clone()))
            .merge(create_stock_item_read_routes(self.stock_item_service.clone()))
    }

    // <<< CUSTOM METHODS
    // END CUSTOM
}

/// Builder for InventoryModule
pub struct InventoryModuleBuilder {
    db_pool: Option<PgPool>,
}

impl InventoryModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<InventoryModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // PickingBatch service
        let picking_batch_repository = Arc::new(PickingBatchRepository::new(db_pool.clone()));
        let picking_batch_service = Arc::new(PickingBatchService::with_repository(picking_batch_repository.clone()));

        // DeliveryNote service
        let delivery_note_repository = Arc::new(DeliveryNoteRepository::new(db_pool.clone()));
        let delivery_note_service = Arc::new(DeliveryNoteService::with_repository(delivery_note_repository.clone()));

        // DeliveryNoteItem service
        let delivery_note_item_repository = Arc::new(DeliveryNoteItemRepository::new(db_pool.clone()));
        let delivery_note_item_service = Arc::new(DeliveryNoteItemService::with_repository(delivery_note_item_repository.clone()));

        // InventoryCompanySetting service
        let inventory_company_setting_repository = Arc::new(InventoryCompanySettingRepository::new(db_pool.clone()));
        let inventory_company_setting_service = Arc::new(InventoryCompanySettingService::with_repository(inventory_company_setting_repository.clone()));

        // LandedCost service
        let landed_cost_repository = Arc::new(LandedCostRepository::new(db_pool.clone()));
        let landed_cost_service = Arc::new(LandedCostService::with_repository(landed_cost_repository.clone()));

        // LandedCostLine service
        let landed_cost_line_repository = Arc::new(LandedCostLineRepository::new(db_pool.clone()));
        let landed_cost_line_service = Arc::new(LandedCostLineService::with_repository(landed_cost_line_repository.clone()));

        // LandedCostAdjustmentLine service
        let landed_cost_adjustment_line_repository = Arc::new(LandedCostAdjustmentLineRepository::new(db_pool.clone()));
        let landed_cost_adjustment_line_service = Arc::new(LandedCostAdjustmentLineService::with_repository(landed_cost_adjustment_line_repository.clone()));

        // Location service
        let location_repository = Arc::new(LocationRepository::new(db_pool.clone()));
        let location_service = Arc::new(LocationService::with_repository(location_repository.clone()));

        // StockMove service
        let stock_move_repository = Arc::new(StockMoveRepository::new(db_pool.clone()));
        let stock_move_service = Arc::new(StockMoveService::with_repository(stock_move_repository.clone()));

        // StockMoveLine service
        let stock_move_line_repository = Arc::new(StockMoveLineRepository::new(db_pool.clone()));
        let stock_move_line_service = Arc::new(StockMoveLineService::with_repository(stock_move_line_repository.clone()));

        // OperationType service
        let operation_type_repository = Arc::new(OperationTypeRepository::new(db_pool.clone()));
        let operation_type_service = Arc::new(OperationTypeService::with_repository(operation_type_repository.clone()));

        // Transfer service
        let transfer_repository = Arc::new(TransferRepository::new(db_pool.clone()));
        let transfer_service = Arc::new(TransferService::with_repository(transfer_repository.clone()));

        // Route service
        let route_repository = Arc::new(RouteRepository::new(db_pool.clone()));
        let route_service = Arc::new(RouteService::with_repository(route_repository.clone()));

        // RouteRule service
        let route_rule_repository = Arc::new(RouteRuleRepository::new(db_pool.clone()));
        let route_rule_service = Arc::new(RouteRuleService::with_repository(route_rule_repository.clone()));

        // ReorderingRule service
        let reordering_rule_repository = Arc::new(ReorderingRuleRepository::new(db_pool.clone()));
        let reordering_rule_service = Arc::new(ReorderingRuleService::with_repository(reordering_rule_repository.clone()));

        // PurchaseReceipt service
        let purchase_receipt_repository = Arc::new(PurchaseReceiptRepository::new(db_pool.clone()));
        let purchase_receipt_service = Arc::new(PurchaseReceiptService::with_repository(purchase_receipt_repository.clone()));

        // PurchaseReceiptItem service
        let purchase_receipt_item_repository = Arc::new(PurchaseReceiptItemRepository::new(db_pool.clone()));
        let purchase_receipt_item_service = Arc::new(PurchaseReceiptItemService::with_repository(purchase_receipt_item_repository.clone()));

        // Quant service
        let quant_repository = Arc::new(QuantRepository::new(db_pool.clone()));
        let quant_service = Arc::new(QuantService::with_repository(quant_repository.clone()));

        // Scrap service
        let scrap_repository = Arc::new(ScrapRepository::new(db_pool.clone()));
        let scrap_service = Arc::new(ScrapService::with_repository(scrap_repository.clone()));

        // ScrapReasonTag service
        let scrap_reason_tag_repository = Arc::new(ScrapReasonTagRepository::new(db_pool.clone()));
        let scrap_reason_tag_service = Arc::new(ScrapReasonTagService::with_repository(scrap_reason_tag_repository.clone()));

        // StockEntry service
        let stock_entry_repository = Arc::new(StockEntryRepository::new(db_pool.clone()));
        let stock_entry_service = Arc::new(StockEntryService::with_repository(stock_entry_repository.clone()));

        // StockEntryItem service
        let stock_entry_item_repository = Arc::new(StockEntryItemRepository::new(db_pool.clone()));
        let stock_entry_item_service = Arc::new(StockEntryItemService::with_repository(stock_entry_item_repository.clone()));

        // StockLedgerEntry service
        let stock_ledger_entry_repository = Arc::new(StockLedgerEntryRepository::new(db_pool.clone()));
        let stock_ledger_entry_service = Arc::new(StockLedgerEntryService::with_repository(stock_ledger_entry_repository.clone()));

        // Bin service
        let bin_repository = Arc::new(BinRepository::new(db_pool.clone()));
        let bin_service = Arc::new(BinService::with_repository(bin_repository.clone()));

        // StockReconciliation service
        let stock_reconciliation_repository = Arc::new(StockReconciliationRepository::new(db_pool.clone()));
        let stock_reconciliation_service = Arc::new(StockReconciliationService::with_repository(stock_reconciliation_repository.clone()));

        // StockReconciliationItem service
        let stock_reconciliation_item_repository = Arc::new(StockReconciliationItemRepository::new(db_pool.clone()));
        let stock_reconciliation_item_service = Arc::new(StockReconciliationItemService::with_repository(stock_reconciliation_item_repository.clone()));

        // PackageType service
        let package_type_repository = Arc::new(PackageTypeRepository::new(db_pool.clone()));
        let package_type_service = Arc::new(PackageTypeService::with_repository(package_type_repository.clone()));

        // StorageCategory service
        let storage_category_repository = Arc::new(StorageCategoryRepository::new(db_pool.clone()));
        let storage_category_service = Arc::new(StorageCategoryService::with_repository(storage_category_repository.clone()));

        // StorageCategoryCapacity service
        let storage_category_capacity_repository = Arc::new(StorageCategoryCapacityRepository::new(db_pool.clone()));
        let storage_category_capacity_service = Arc::new(StorageCategoryCapacityService::with_repository(storage_category_capacity_repository.clone()));

        // PutawayRule service
        let putaway_rule_repository = Arc::new(PutawayRuleRepository::new(db_pool.clone()));
        let putaway_rule_service = Arc::new(PutawayRuleService::with_repository(putaway_rule_repository.clone()));

        // Lot service
        let lot_repository = Arc::new(LotRepository::new(db_pool.clone()));
        let lot_service = Arc::new(LotService::with_repository(lot_repository.clone()));

        // Package service
        let package_repository = Arc::new(PackageRepository::new(db_pool.clone()));
        let package_service = Arc::new(PackageService::with_repository(package_repository.clone()));

        // Warehouse service
        let warehouse_repository = Arc::new(WarehouseRepository::new(db_pool.clone()));
        let warehouse_service = Arc::new(WarehouseService::with_repository(warehouse_repository.clone()));

        // StockItem service
        let stock_item_repository = Arc::new(StockItemRepository::new(db_pool.clone()));
        let stock_item_service = Arc::new(StockItemService::with_repository(stock_item_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(InventoryModule {
            picking_batch_service,
            delivery_note_service,
            delivery_note_item_service,
            inventory_company_setting_service,
            landed_cost_service,
            landed_cost_line_service,
            landed_cost_adjustment_line_service,
            location_service,
            stock_move_service,
            stock_move_line_service,
            operation_type_service,
            transfer_service,
            route_service,
            route_rule_service,
            reordering_rule_service,
            purchase_receipt_service,
            purchase_receipt_item_service,
            quant_service,
            scrap_service,
            scrap_reason_tag_service,
            stock_entry_service,
            stock_entry_item_service,
            stock_ledger_entry_service,
            bin_service,
            stock_reconciliation_service,
            stock_reconciliation_item_service,
            package_type_service,
            storage_category_service,
            storage_category_capacity_service,
            putaway_rule_service,
            lot_service,
            package_service,
            warehouse_service,
            stock_item_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for InventoryModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
