//! Use case type aliases for GoodsReceiptItem aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateGoodsReceiptItemDto, UpdateGoodsReceiptItemDto};
use crate::application::service::GoodsReceiptItemService;
use crate::domain::entity::GoodsReceiptItem;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateGoodsReceiptItemUseCase = CreateUseCase<GoodsReceiptItem, CreateGoodsReceiptItemDto, GoodsReceiptItemService>;
pub type UpdateGoodsReceiptItemUseCase = UpdateUseCase<GoodsReceiptItem, UpdateGoodsReceiptItemDto, GoodsReceiptItemService>;
pub type GetGoodsReceiptItemUseCase    = GetUseCase<GoodsReceiptItem, GoodsReceiptItemService>;
pub type DeleteGoodsReceiptItemUseCase = DeleteUseCase<GoodsReceiptItem, GoodsReceiptItemService>;
pub type ListGoodsReceiptItemUseCase   = ListUseCase<GoodsReceiptItem, GoodsReceiptItemService>;

// <<< CUSTOM
// END CUSTOM
