//! Use case type aliases for PurchaseReceipt aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreatePurchaseReceiptDto, UpdatePurchaseReceiptDto};
use crate::application::service::PurchaseReceiptService;
use crate::domain::entity::PurchaseReceipt;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreatePurchaseReceiptUseCase = CreateUseCase<PurchaseReceipt, CreatePurchaseReceiptDto, PurchaseReceiptService>;
pub type UpdatePurchaseReceiptUseCase = UpdateUseCase<PurchaseReceipt, UpdatePurchaseReceiptDto, PurchaseReceiptService>;
pub type GetPurchaseReceiptUseCase    = GetUseCase<PurchaseReceipt, PurchaseReceiptService>;
pub type DeletePurchaseReceiptUseCase = DeleteUseCase<PurchaseReceipt, PurchaseReceiptService>;
pub type ListPurchaseReceiptUseCase   = ListUseCase<PurchaseReceipt, PurchaseReceiptService>;

// <<< CUSTOM
// END CUSTOM
