//! Use case type aliases for StockBatch aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateStockBatchDto, UpdateStockBatchDto};
use crate::application::service::StockBatchService;
use crate::domain::entity::StockBatch;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateStockBatchUseCase = CreateUseCase<StockBatch, CreateStockBatchDto, StockBatchService>;
pub type UpdateStockBatchUseCase = UpdateUseCase<StockBatch, UpdateStockBatchDto, StockBatchService>;
pub type GetStockBatchUseCase    = GetUseCase<StockBatch, StockBatchService>;
pub type DeleteStockBatchUseCase = DeleteUseCase<StockBatch, StockBatchService>;
pub type ListStockBatchUseCase   = ListUseCase<StockBatch, StockBatchService>;

// <<< CUSTOM
// END CUSTOM
