//! Use case type aliases for StockEntryItem aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateStockEntryItemDto, UpdateStockEntryItemDto};
use crate::application::service::StockEntryItemService;
use crate::domain::entity::StockEntryItem;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateStockEntryItemUseCase = CreateUseCase<StockEntryItem, CreateStockEntryItemDto, StockEntryItemService>;
pub type UpdateStockEntryItemUseCase = UpdateUseCase<StockEntryItem, UpdateStockEntryItemDto, StockEntryItemService>;
pub type GetStockEntryItemUseCase    = GetUseCase<StockEntryItem, StockEntryItemService>;
pub type DeleteStockEntryItemUseCase = DeleteUseCase<StockEntryItem, StockEntryItemService>;
pub type ListStockEntryItemUseCase   = ListUseCase<StockEntryItem, StockEntryItemService>;

// <<< CUSTOM
// END CUSTOM
